// Command genparity aggregates the per-library parity.json files that each
// malcolmston/* port emits (via the parity CI pipeline) into the landing's
// web/src/parity.ts, so the go aggregator always reports the current
// upstream-parity numbers.
//
// Run it from the repo root once the library submodules have been bumped to
// commits that contain a parity.json:
//
//	go run ./genparity
//
// It scans every top-level directory for a parity.json and rewrites
// web/src/parity.ts. Libraries without a parity.json are simply omitted.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// parityFile mirrors the schema each port writes to its parity.json.
type parityFile struct {
	Repo                string `json:"repo"`
	Upstream            string `json:"upstream"`
	ParityBefore        string `json:"parityBefore"`
	ParityAfter         string `json:"parityAfter"`
	UpstreamCasesSynced int    `json:"upstreamCasesSynced"`
	GapsClosed          int    `json:"gapsClosed"`
}

func main() {
	rootFlag := flag.String("root", ".", "directory holding the library repos/submodules (each with a parity.json)")
	outFlag := flag.String("out", "", "output path for parity.ts (default <root>/web/src/parity.ts)")
	flag.Parse()
	root := *rootFlag
	// Backward-compatible positional root argument.
	if flag.NArg() > 0 {
		root = flag.Arg(0)
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		fatal(err)
	}
	type rec struct {
		id string
		p  parityFile
	}
	var recs []rec
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		b, err := os.ReadFile(filepath.Join(root, e.Name(), "parity.json"))
		if err != nil {
			continue
		}
		var p parityFile
		if json.Unmarshal(b, &p) != nil {
			continue
		}
		id := p.Repo
		if id == "" {
			id = e.Name()
		}
		recs = append(recs, rec{id, p})
	}
	sort.Slice(recs, func(i, j int) bool { return recs[i].id < recs[j].id })

	var b strings.Builder
	b.WriteString(header)
	for _, r := range recs {
		fmt.Fprintf(&b, "  %s: { upstream: %q, before: %q, after: %q, casesSynced: %d, gapsClosed: %d },\n",
			tsKey(r.id), r.p.Upstream, r.p.ParityBefore, r.p.ParityAfter, r.p.UpstreamCasesSynced, r.p.GapsClosed)
	}
	b.WriteString("};\n")

	out := *outFlag
	if out == "" {
		out = filepath.Join(root, "web", "src", "parity.ts")
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("genparity: wrote %s with %d libraries\n", out, len(recs))
}

// tsKey quotes an object key when it is not a plain JS identifier.
func tsKey(k string) string {
	plain := k != ""
	for i, r := range k {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9') {
			continue
		}
		plain = false
		break
	}
	if plain {
		return k
	}
	return "'" + strings.ReplaceAll(k, "'", "\\'") + "'"
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "genparity:", err)
	os.Exit(1)
}

const header = `// Upstream-parity metrics per library, aggregated from each repo's parity.json
// (emitted by the parity CI pipeline / the upstream-parity audit). Each library
// port is measured against the ORIGINAL library it mirrors by syncing that
// library's own test suite into Go and closing the gaps those tests expose.
//
// GENERATED by ` + "`go run ./genparity`" + ` — do not edit by hand.

export interface Parity {
  upstream: string;
  before: string;
  after: string;
  casesSynced: number;
  gapsClosed: number;
}

// PARITY is keyed by Lib.id.
export const PARITY: Record<string, Parity> = {
`
