package delaunay

import (
	"math"
	"math/rand"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// Values that can be derived by hand.
// ---------------------------------------------------------------------------

func TestVoronoiOfTwoPointsIsAHalfPlaneSplit(t *testing.T) {
	// Two points on the x axis: the boundary is the vertical bisector x = 5,
	// and each cell is exactly the half of the extent on its own side.
	d := New([]Point{{2, 0}, {8, 0}})
	v := d.Voronoi(0, -5, 10, 5)
	for i, wantSide := range []float64{2, 8} {
		ring := v.CellPolygon(i)
		if ring == nil {
			t.Fatalf("cell %d is nil", i)
		}
		if a := math.Abs(testPolygonArea(ring)) / 2; math.Abs(a-50) > 1e-9 {
			t.Errorf("cell %d area = %v, want 50", i, a)
		}
		// Every vertex is on the correct side of x = 5, or exactly on it.
		for _, p := range ring {
			if (wantSide < 5 && p.X > 5+1e-12) || (wantSide > 5 && p.X < 5-1e-12) {
				t.Errorf("cell %d has vertex %v on the wrong side of x=5", i, p)
			}
		}
	}
}

func TestVoronoiBoundsAndRenderShapes(t *testing.T) {
	d := New([]Point{{1, 1}, {3, 1}, {2, 3}})
	v := d.Voronoi(0, 0, 4, 4)
	if got, want := v.RenderBounds(), "M0,0h4v4h-4Z"; got != want {
		t.Errorf("RenderBounds() = %q, want %q", got, want)
	}
	xmin, ymin, xmax, ymax := v.Extent()
	if xmin != 0 || ymin != 0 || xmax != 4 || ymax != 4 {
		t.Errorf("Extent() = %v %v %v %v", xmin, ymin, xmax, ymax)
	}
	if v.Delaunay() != d {
		t.Error("Delaunay() did not return the triangulation it was built from")
	}
	for i := 0; i < 3; i++ {
		s := v.RenderCell(i)
		if !strings.HasPrefix(s, "M") || !strings.HasSuffix(s, "Z") {
			t.Errorf("RenderCell(%d) = %q, want a closed subpath", i, s)
		}
	}
	if !strings.HasPrefix(v.Render(), "M") {
		t.Errorf("Render() = %q", v.Render())
	}
}

func TestInvalidExtentPanics(t *testing.T) {
	d := New([]Point{{0, 0}, {1, 1}})
	for _, tc := range [][4]float64{
		{10, 0, 0, 10},
		{0, 10, 10, 0},
		{0, 0, math.NaN(), 10},
	} {
		func() {
			defer func() {
				if recover() == nil {
					t.Errorf("Voronoi%v did not panic", tc)
				}
			}()
			d.Voronoi(tc[0], tc[1], tc[2], tc[3])
		}()
	}
}

// ---------------------------------------------------------------------------
// Properties.
// ---------------------------------------------------------------------------

// TestCellContainsItsOwnPoint is the defining property of a Voronoi cell.
func TestCellContainsItsOwnPoint(t *testing.T) {
	for seed := int64(0); seed < 60; seed++ {
		rng := rand.New(rand.NewSource(seed + 5000))
		n := 2 + rng.Intn(40)
		pts := randomPoints(rng, n, 100)
		d := New(pts)
		v := d.Voronoi(0, 0, 100, 100)
		for _, c := range v.CellPolygons() {
			p := d.Points()[c.Index]
			if !testInPolygon(c.Polygon, p) {
				t.Fatalf("seed %d: cell %d does not contain its own point %v (ring %v)",
					seed, c.Index, p, c.Polygon)
			}
		}
	}
}

// TestCellsTileTheExtent checks that the cells partition the clipping rectangle
// — no gaps and no overlaps — by comparing the total area against the
// rectangle's, and by checking that no two cells overlap at sampled points.
func TestCellsTileTheExtent(t *testing.T) {
	for seed := int64(0); seed < 60; seed++ {
		rng := rand.New(rand.NewSource(seed + 6000))
		n := 1 + rng.Intn(30)
		pts := randomPoints(rng, n, 100)
		d := New(pts)
		v := d.Voronoi(0, 0, 100, 100)

		total := 0.0
		cells := v.CellPolygons()
		for _, c := range cells {
			total += math.Abs(testPolygonArea(c.Polygon)) / 2
		}
		if math.Abs(total-10000) > 1e-6 {
			t.Fatalf("seed %d (n=%d): cells cover %v, want 10000", seed, n, total)
		}

		// No overlaps: a sampled interior point falls strictly inside at most
		// one cell.
		for q := 0; q < 40; q++ {
			qx, qy := rng.Float64()*100, rng.Float64()*100
			hits := 0
			for _, c := range cells {
				if testInPolygon(c.Polygon, Point{qx, qy}) {
					hits++
				}
			}
			if hits == 0 {
				t.Fatalf("seed %d: (%v,%v) is in no cell", seed, qx, qy)
			}
		}
	}
}

// TestCellOfAQueryPointIsItsNearestPoint ties the geometry back to the
// definition: the cell a point falls in is generated by its nearest neighbor.
func TestCellOfAQueryPointIsItsNearestPoint(t *testing.T) {
	for seed := int64(0); seed < 30; seed++ {
		rng := rand.New(rand.NewSource(seed + 7000))
		pts := randomPoints(rng, 25, 100)
		d := New(pts)
		v := d.Voronoi(0, 0, 100, 100)
		cells := v.CellPolygons()
		for q := 0; q < 60; q++ {
			qx, qy := rng.Float64()*100, rng.Float64()*100
			best, bestD := -1, math.Inf(1)
			for i, p := range pts {
				if dd := (p.X-qx)*(p.X-qx) + (p.Y-qy)*(p.Y-qy); dd < bestD {
					best, bestD = i, dd
				}
			}
			for _, c := range cells {
				if !testInPolygon(c.Polygon, Point{qx, qy}) {
					continue
				}
				p := pts[c.Index]
				dd := (p.X-qx)*(p.X-qx) + (p.Y-qy)*(p.Y-qy)
				// A query on a shared boundary is legitimately in both cells,
				// so compare distances rather than indices.
				if dd > bestD+1e-6 {
					t.Fatalf("seed %d: (%v,%v) is in cell %d (d2=%v) but nearest is %d (d2=%v)",
						seed, qx, qy, c.Index, dd, best, bestD)
				}
			}
		}
	}
}

// TestSharedBoundariesAreEquidistant checks the other defining property: the
// segment two cells share lies on the perpendicular bisector of the two points
// that generate them, so every point of it is the same distance from both.
func TestSharedBoundariesAreEquidistant(t *testing.T) {
	checked := 0
	for seed := int64(0); seed < 40; seed++ {
		rng := rand.New(rand.NewSource(seed + 8000))
		pts := randomPoints(rng, 20, 100)
		d := New(pts)
		v := d.Voronoi(0, 0, 100, 100)
		for i := range pts {
			ci := v.CellPolygon(i)
			if ci == nil {
				continue
			}
			for _, j := range v.Neighbors(i) {
				cj := v.CellPolygon(j)
				if cj == nil {
					continue
				}
				a, b, ok := sharedEdge(ci, cj)
				if !ok {
					t.Fatalf("seed %d: cells %d and %d are neighbors with no shared edge", seed, i, j)
				}
				pi, pj := pts[i], pts[j]
				// Both endpoints and the midpoint: three points of a segment
				// are more than enough to pin it to the bisector.
				for _, s := range []Point{a, b, {(a.X + b.X) / 2, (a.Y + b.Y) / 2}} {
					di := math.Hypot(s.X-pi.X, s.Y-pi.Y)
					dj := math.Hypot(s.X-pj.X, s.Y-pj.Y)
					if math.Abs(di-dj) > 1e-6*math.Max(1, di) {
						t.Fatalf("seed %d: boundary point %v between %d %v and %d %v is %v from one and %v from the other",
							seed, s, i, pi, j, pj, di, dj)
					}
					checked++
				}
			}
		}
	}
	if checked == 0 {
		t.Fatal("no shared boundaries were checked")
	}
}

// sharedEdge finds the segment two closed cell rings have in common. Adjacent
// cells traverse it in opposite directions, which is what identifies it and
// distinguishes it from a merely shared vertex.
func sharedEdge(ci, cj []Point) (Point, Point, bool) {
	for a := 0; a+1 < len(ci); a++ {
		for b := 0; b+1 < len(cj); b++ {
			if ci[a] == cj[b+1] && ci[a+1] == cj[b] {
				return ci[a], ci[a+1], true
			}
		}
	}
	return Point{}, Point{}, false
}

func TestVoronoiContainsMatchesNearest(t *testing.T) {
	for seed := int64(0); seed < 20; seed++ {
		rng := rand.New(rand.NewSource(seed + 9000))
		pts := randomPoints(rng, 30, 100)
		d := New(pts)
		v := d.Voronoi(0, 0, 100, 100)
		for q := 0; q < 50; q++ {
			qx, qy := rng.Float64()*100, rng.Float64()*100
			best, bestD := -1, math.Inf(1)
			for i, p := range pts {
				if dd := (p.X-qx)*(p.X-qx) + (p.Y-qy)*(p.Y-qy); dd < bestD {
					best, bestD = i, dd
				}
			}
			if !v.Contains(best, qx, qy) {
				t.Fatalf("seed %d: Contains(%d, %v, %v) = false for the nearest point", seed, best, qx, qy)
			}
			// And some other cell does not contain it, unless it is tied.
			for i := range pts {
				if i == best {
					continue
				}
				p := pts[i]
				dd := (p.X-qx)*(p.X-qx) + (p.Y-qy)*(p.Y-qy)
				if v.Contains(i, qx, qy) && dd > bestD+1e-9 {
					t.Fatalf("seed %d: Contains(%d) = true although %d is nearer", seed, i, best)
				}
			}
		}
	}
	if got := (&Voronoi{d: New(nil)}).Contains(0, 0, 0); got {
		t.Error("Contains on an empty diagram = true")
	}
}

func TestCellPolygonsAreClosedAndSimple(t *testing.T) {
	for seed := int64(0); seed < 40; seed++ {
		rng := rand.New(rand.NewSource(seed + 10000))
		pts := randomPoints(rng, 3+rng.Intn(25), 100)
		d := New(pts)
		v := d.Voronoi(10, 10, 90, 90)
		for _, c := range v.CellPolygons() {
			ring := c.Polygon
			if len(ring) < 4 {
				t.Fatalf("seed %d: cell %d has only %d vertices", seed, c.Index, len(ring))
			}
			if ring[0] != ring[len(ring)-1] {
				t.Fatalf("seed %d: cell %d is not closed", seed, c.Index)
			}
			// Convex, and wound consistently with every other cell.
			n := len(ring) - 1
			var wind float64
			for k := 0; k < n; k++ {
				a, b, cc := ring[k], ring[(k+1)%n], ring[(k+2)%n]
				s := testCross(a, b, cc)
				if math.Abs(s) < 1e-9 {
					continue
				}
				if wind == 0 {
					wind = s
				} else if (s > 0) != (wind > 0) {
					t.Fatalf("seed %d: cell %d is not convex: %v", seed, c.Index, ring)
				}
			}
			// Entirely inside the clipping rectangle.
			for _, p := range ring {
				if p.X < 10-1e-9 || p.X > 90+1e-9 || p.Y < 10-1e-9 || p.Y > 90+1e-9 {
					t.Fatalf("seed %d: cell %d has vertex %v outside the extent", seed, c.Index, p)
				}
			}
		}
	}
}

func TestVoronoiNeighborsAreSymmetric(t *testing.T) {
	for seed := int64(0); seed < 20; seed++ {
		rng := rand.New(rand.NewSource(seed + 11000))
		pts := randomPoints(rng, 25, 100)
		v := New(pts).Voronoi(0, 0, 100, 100)
		for i := range pts {
			for _, j := range v.Neighbors(i) {
				found := false
				for _, k := range v.Neighbors(j) {
					if k == i {
						found = true
					}
				}
				if !found {
					t.Fatalf("seed %d: cell %d borders %d but not the reverse", seed, i, j)
				}
			}
		}
	}
}

func TestVoronoiCellsOutsideExtent(t *testing.T) {
	// Points far to one side: only the cells whose region reaches the rectangle
	// have geometry, and they still tile it.
	pts := []Point{{-500, 50}, {-501, 51}, {600, 50}, {50, 50}}
	v := New(pts).Voronoi(0, 0, 100, 100)
	total := 0.0
	for _, c := range v.CellPolygons() {
		total += math.Abs(testPolygonArea(c.Polygon)) / 2
	}
	if math.Abs(total-10000) > 1e-6 {
		t.Errorf("cells cover %v of the 10000-unit extent", total)
	}
}

func TestVoronoiWithDuplicatePoints(t *testing.T) {
	pts := []Point{{10, 10}, {90, 10}, {50, 90}, {10, 10}, {90, 10}}
	d := New(pts)
	v := d.Voronoi(0, 0, 100, 100)
	inedges := d.Inedges()
	total := 0.0
	for i := range pts {
		ring := v.CellPolygon(i)
		if inedges[i] == -1 {
			if ring != nil {
				t.Errorf("dropped duplicate %d still has a cell %v", i, ring)
			}
			continue
		}
		total += math.Abs(testPolygonArea(ring)) / 2
	}
	if math.Abs(total-10000) > 1e-6 {
		t.Errorf("cells cover %v of the 10000-unit extent", total)
	}
}

func TestVoronoiOfCollinearPointsTiles(t *testing.T) {
	for n := 3; n <= 8; n++ {
		var pts []Point
		for i := 0; i < n; i++ {
			pts = append(pts, Point{float64(i) * 10, 50})
		}
		v := New(pts).Voronoi(0, 0, 100, 100)
		total := 0.0
		for _, c := range v.CellPolygons() {
			total += math.Abs(testPolygonArea(c.Polygon)) / 2
		}
		if math.Abs(total-10000) > 1e-3 {
			t.Errorf("n=%d: collinear cells cover %v of 10000", n, total)
		}
	}
}

func BenchmarkTriangulate1000(b *testing.B) {
	rng := rand.New(rand.NewSource(1))
	pts := randomPoints(rng, 1000, 1000)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		New(pts)
	}
}
