// Command streamlit-example exercises github.com/malcolmston/streamlit as an
// outside consumer of the published module.
//
// The library is a Streamlit-style data-app framework: an app function builds
// an element tree by calling display/widget methods on a *st.Session, and the
// embedded frontend posts widget events back to rerun the app.
//
// Because the package exposes no in-process render entry point (see README
// "Holes"), this program drives the app through st.Handler mounted on an
// httptest server bound to a random localhost port, inspects the JSON element
// trees that come back, and shuts the server down. It always terminates.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"sync/atomic"
	"time"

	"github.com/malcolmston/streamlit/st"
)

// ---------------------------------------------------------------------------
// Wire protocol.
//
// HOLE: the request/response types for POST /api/run (runRequest/runResponse)
// and the widget event struct are unexported, so any external driver, test
// harness, or alternative frontend has to redeclare them by hand from the
// server source. Only st.Element is exported.
// ---------------------------------------------------------------------------

type event struct {
	Key    string         `json:"key"`
	Value  any            `json:"value"`
	Button bool           `json:"button,omitempty"`
	Form   string         `json:"form,omitempty"`
	Values map[string]any `json:"values,omitempty"`
}

type runRequest struct {
	SessionID string `json:"sessionId"`
	Event     *event `json:"event,omitempty"`
}

type runResponse struct {
	SessionID string      `json:"sessionId"`
	Tree      *st.Element `json:"tree"`
}

// Row is a struct row rendered via reflection by DataFrame/Table.
type Row struct {
	Region  string
	Units   int
	Revenue float64
}

// cacheCalls counts how many times the expensive computation actually ran.
var cacheCalls int64

// buildApp returns the app function under test.
func buildApp() func(*st.Session) {
	return func(s *st.Session) {
		s.SetPageConfig("Quarterly Report", "chart")

		// ---- Sidebar: controls -------------------------------------------
		sb := s.Sidebar()
		sb.Header("Controls")
		region := sb.SelectBox("Region", []string{"EMEA", "AMER", "APAC"}, "region")
		smooth := sb.Slider("Smoothing", 0, 10, 3, 1, "smooth")
		showRaw := sb.Checkbox("Show raw rows", false, "showraw")
		bins := sb.NumberInput("Histogram bins", 5, "bins")
		mode := sb.SegmentedControl("Mode", []string{"Compact", "Detailed"}, "mode")
		sb.Divider()

		// ---- Text / markdown --------------------------------------------
		s.Title("Quarterly Report")
		s.Subheader("Region: " + region)
		s.Markdown("Revenue for **" + region + "** with smoothing `" + fmt.Sprint(smooth) + "`.")
		s.Caption("Generated by the Go port of Streamlit.")
		s.Latex(`\sum_{i=1}^{n} r_i`)
		s.Code("rows := s.Cache(\"rows\", load)", "go")
		s.Info("Interactive widgets rerun the app top to bottom.")
		s.Divider()

		// ---- Caching -----------------------------------------------------
		// Process-wide memoisation: compute runs once across every rerun and
		// every session.
		cached := s.Cache("rows:"+region, func() any {
			atomic.AddInt64(&cacheCalls, 1)
			return []Row{
				{Region: region, Units: 120, Revenue: 15400.50},
				{Region: region, Units: 98, Revenue: 12010.25},
				{Region: region, Units: 143, Revenue: 18999.00},
			}
		}, time.Minute)
		rows := cached.([]Row)

		// ---- Session state ------------------------------------------------
		s.State.Set("runs", s.State.GetInt("runs", 0)+1)
		s.Metric("Runs this session", fmt.Sprint(s.State.GetInt("runs", 0)), "+1")

		// ---- Layout: columns of metrics ------------------------------------
		cols := s.Columns(3)
		var units int
		var revenue float64
		for _, r := range rows {
			units += r.Units
			revenue += r.Revenue
		}
		cols[0].Metric("Units", fmt.Sprint(units), "+12")
		cols[1].Metric("Revenue", fmt.Sprintf("$%.2f", revenue), "+3.1%")
		cols[2].MetricColored("Churn", "1.8%", "-0.4%", "inverse")

		// ---- Layout: tabs holding charts and data --------------------------
		tabs := s.Tabs([]string{"Trend", "Breakdown", "Data"})

		series := []float64{10, 14, 9, 22, 18, 27, 31}
		other := []float64{6, 8, 12, 11, 15, 14, 20}
		tabs[0].LineChart(series, other)
		tabs[0].AreaChart(series)
		tabs[0].BarChart(other)

		tabs[1].PieChart([]float64{40, 35, 25}, []string{"EMEA", "AMER", "APAC"})
		tabs[1].ScatterChart([]float64{1, 2, 3, 4}, []float64{2, 4, 3, 6})
		tabs[1].Histogram(series, int(bins))
		tabs[1].Map([]st.MapPoint{{Lat: 51.5, Lng: -0.12}, {Lat: 40.7, Lng: -74.0}})

		tabs[2].DataFrame(rows, "Sortable revenue by region")
		if showRaw {
			tabs[2].Table([][]string{
				{"Region", "Units"},
				{region, fmt.Sprint(units)},
			}, "Raw")
		}
		tabs[2].JSON(map[string]any{"region": region, "units": units}, true)

		// ---- Expander + bordered container ---------------------------------
		ex := s.Expander("Details", mode == "Detailed")
		ex.Text("Mode is " + mode)
		ex.Progress(float64(smooth) / 10)
		bc := s.BorderedContainer()
		bc.Badge("beta", "green")
		bc.Help(struct{ A int }{1})

		// ---- Form: batched widgets ------------------------------------------
		f := s.Form("filters")
		name := f.TextInput("Analyst", "", "analyst")
		note := f.TextArea("Note", "", "note")
		flag := f.Toggle("Publish", false, "publish")
		if f.FormSubmitButton("Apply") {
			s.Success("Applied by " + name + " (publish=" + fmt.Sprint(flag) + "): " + note)
		}

		// ---- Buttons and other widgets ---------------------------------------
		if s.Button("Refresh", "refresh") {
			s.Toast("Refreshed", "check")
			s.Balloons()
		}
		if s.PrimaryButton("Export", "export") {
			s.Info("Exporting...")
		}
		s.DownloadButton("Download CSV", "report.csv", []byte("Region,Units\nEMEA,361\n"), "dl")
		s.MultiSelect("Compare", []string{"EMEA", "AMER", "APAC"}, "compare")
		s.Radio("Grain", []string{"Day", "Week"}, "grain")
		s.Pills("Tags", []string{"ok", "urgent"}, "tags")
		s.ColorPicker("Accent", "#ff8800", "accent")
		s.DateInput("As of", "2026-08-10", "asof")
		s.SelectSlider("Bucket", []string{"S", "M", "L"}, "bucket")
		s.Feedback("stars", "fb")
		s.LinkButton("Docs", "https://example.invalid/docs")

		st1 := s.Status("Loading data", "complete")
		st1.Text("done")

		if smooth > 9 {
			s.Warning("Smoothing at maximum; stopping early.")
			s.Stop() // must not leak a panic out of the run
		}
		s.Text("Reached end of app.")
	}
}

// ---------------------------------------------------------------------------
// Driver helpers.
// ---------------------------------------------------------------------------

func run(base, sessionID string, ev *event) runResponse {
	body, err := json.Marshal(runRequest{SessionID: sessionID, Event: ev})
	must(err)
	resp, err := http.Post(base+"/api/run", "application/json", bytes.NewReader(body))
	must(err)
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		fail(fmt.Sprintf("POST /api/run -> %d: %s", resp.StatusCode, b))
	}
	var out runResponse
	must(json.NewDecoder(resp.Body).Decode(&out))
	if out.Tree == nil {
		fail("server returned a nil element tree")
	}
	return out
}

func find(root *st.Element, typ string) *st.Element {
	if root == nil {
		return nil
	}
	if root.Type == typ {
		return root
	}
	for _, c := range root.Children {
		if got := find(c, typ); got != nil {
			return got
		}
	}
	return nil
}

func findKey(root *st.Element, key string) *st.Element {
	if root == nil {
		return nil
	}
	if root.Key == key {
		return root
	}
	for _, c := range root.Children {
		if got := findKey(c, key); got != nil {
			return got
		}
	}
	return nil
}

func countByType(root *st.Element, counts map[string]int) {
	if root == nil {
		return
	}
	counts[root.Type]++
	for _, c := range root.Children {
		countByType(c, counts)
	}
}

func depth(root *st.Element) int {
	if root == nil {
		return 0
	}
	best := 0
	for _, c := range root.Children {
		if d := depth(c); d > best {
			best = d
		}
	}
	return best + 1
}

func prop(el *st.Element, name string) any {
	if el == nil || el.Props == nil {
		return nil
	}
	return el.Props[name]
}

func section(title string) { fmt.Printf("\n== %s ==\n", title) }

func check(label string, ok bool, detail string) {
	status := "OK  "
	if !ok {
		status = "FAIL"
	}
	fmt.Printf("  [%s] %s: %s\n", status, label, detail)
	if !ok {
		failed = true
	}
}

var failed bool

func must(err error) {
	if err != nil {
		fail(err.Error())
	}
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "fatal:", msg)
	os.Exit(1)
}

// ---------------------------------------------------------------------------

func main() {
	st.CacheClear()

	srv := httptest.NewServer(st.Handler(buildApp()))
	defer srv.Close()
	fmt.Println("app mounted on ephemeral localhost server:", srv.URL)

	// --- 1. First run -----------------------------------------------------
	section("1. initial render")
	r1 := run(srv.URL, "", nil)
	fmt.Println("  session id:", r1.SessionID[:8]+"...")
	counts := map[string]int{}
	countByType(r1.Tree, counts)
	fmt.Printf("  tree root=%q depth=%d distinct element types=%d\n",
		r1.Tree.Type, depth(r1.Tree), len(counts))
	for _, t := range []string{"title", "markdown", "latex", "code", "metric",
		"columns", "tabs", "chart", "table", "form", "slider", "selectbox", "map"} {
		fmt.Printf("    %-10s x%d\n", t, counts[t])
	}
	check("root has sidebar + main regions",
		len(r1.Tree.Children) == 2 && r1.Tree.Children[0].Type == "sidebar" && r1.Tree.Children[1].Type == "main",
		fmt.Sprintf("children=%d", len(r1.Tree.Children)))
	check("page config recorded", find(r1.Tree, "root") != nil,
		fmt.Sprintf("root props=%v", r1.Tree.Props))
	check("app reached its final element", find(r1.Tree, "text") != nil, "text element present")

	// --- 2. Text / markdown ------------------------------------------------
	section("2. text and markdown")
	fmt.Printf("  title  = %q\n", prop(find(r1.Tree, "title"), "text"))
	fmt.Printf("  md     = %q\n", prop(find(r1.Tree, "markdown"), "text"))
	fmt.Printf("  latex  = %q\n", prop(find(r1.Tree, "latex"), "expr"))
	c := find(r1.Tree, "code")
	fmt.Printf("  code   = lang=%v %q\n", prop(c, "lang"), prop(c, "code"))
	fmt.Printf("  alert  = kind=%v %q\n", prop(find(r1.Tree, "alert"), "kind"), prop(find(r1.Tree, "alert"), "text"))

	// --- 3. Charts ---------------------------------------------------------
	section("3. charts (server-rendered SVG)")
	chart := find(r1.Tree, "chart")
	svg, _ := prop(chart, "svg").(string)
	check("line chart emits inline SVG",
		strings.HasPrefix(svg, "<svg") && strings.Contains(svg, "polyline"),
		fmt.Sprintf("%d bytes, prefix=%.40q", len(svg), svg))
	mapSVG, _ := prop(find(r1.Tree, "map"), "svg").(string)
	check("map emits inline SVG", strings.HasPrefix(mapSVG, "<svg"),
		fmt.Sprintf("%d bytes", len(mapSVG)))
	fmt.Printf("  chart elements in tree: %d\n", counts["chart"])

	// --- 4. DataFrame ------------------------------------------------------
	section("4. dataframe / table")
	df := find(r1.Tree, "table")
	fmt.Printf("  header   = %v\n", prop(df, "header"))
	fmt.Printf("  rows     = %v\n", prop(df, "rows"))
	fmt.Printf("  caption  = %q sortable=%v\n", prop(df, "caption"), prop(df, "sortable"))
	hdr, _ := prop(df, "header").([]any)
	check("struct fields reflected into header",
		len(hdr) == 3 && hdr[0] == "Region",
		fmt.Sprintf("%v", hdr))

	// --- 5. Widget interaction --------------------------------------------
	section("5. widget events rerun the app")
	r2 := run(srv.URL, r1.SessionID, &event{Key: "region", Value: "APAC"})
	check("selectbox value persisted", prop(findKey(r2.Tree, "region"), "value") == "APAC",
		fmt.Sprintf("region=%v", prop(findKey(r2.Tree, "region"), "value")))
	check("dependent subheader recomputed",
		strings.Contains(fmt.Sprint(prop(find(r2.Tree, "subheader"), "text")), "APAC"),
		fmt.Sprint(prop(find(r2.Tree, "subheader"), "text")))

	r3 := run(srv.URL, r1.SessionID, &event{Key: "smooth", Value: 7.0})
	check("slider value persisted", prop(findKey(r3.Tree, "smooth"), "value") == 7.0,
		fmt.Sprintf("smooth=%v", prop(findKey(r3.Tree, "smooth"), "value")))
	check("slider clamps out-of-range values",
		prop(findKey(run(srv.URL, r1.SessionID, &event{Key: "smooth", Value: 999.0}).Tree, "smooth"), "value") == 10.0,
		"999 -> 10")

	r4 := run(srv.URL, r1.SessionID, &event{Key: "showraw", Value: true})
	tabCount := map[string]int{}
	countByType(r4.Tree, tabCount)
	check("checkbox=true adds the conditional Table", tabCount["table"] == 2,
		fmt.Sprintf("table elements=%d", tabCount["table"]))

	// State persists across reruns of the same session.
	fmt.Printf("  session run counter after 5 runs: %v\n", prop(find(r4.Tree, "metric"), "value"))

	// --- 6. Buttons are transient -----------------------------------------
	section("6. button transience")
	rb := run(srv.URL, r1.SessionID, &event{Key: "refresh", Value: nil, Button: true})
	check("button true for exactly one run", find(rb.Tree, "toast") != nil, "toast rendered on click run")
	rb2 := run(srv.URL, r1.SessionID, nil)
	check("button false on the next run", find(rb2.Tree, "toast") == nil, "toast gone")

	// --- 7. Forms batch until submit --------------------------------------
	section("7. forms commit atomically")
	rf := run(srv.URL, r1.SessionID, &event{
		Key:    "filters",
		Button: true,
		Form:   "filters",
		Values: map[string]any{"analyst": "ada", "note": "looks good", "publish": true},
	})
	var success *st.Element
	for _, e := range findAllAlerts(rf.Tree) {
		if prop(e, "kind") == "success" {
			success = e
		}
	}
	check("staged form values committed together", success != nil,
		fmt.Sprint(prop(success, "text")))
	check("form widgets carry the form key",
		prop(findKey(rf.Tree, "analyst"), "form") == "filters",
		fmt.Sprint(prop(findKey(rf.Tree, "analyst"), "form")))

	// --- 8. Session.Stop halts a run --------------------------------------
	section("8. Session.Stop")
	rs := run(srv.URL, r1.SessionID, &event{Key: "smooth", Value: 10.0})
	check("Stop() truncates the run without panicking",
		find(rs.Tree, "text") == nil || !hasFinalText(rs.Tree),
		"trailing text element absent after Stop")

	// --- 9. Caching --------------------------------------------------------
	section("9. process-wide cache")
	before := atomic.LoadInt64(&cacheCalls)
	for i := 0; i < 3; i++ {
		run(srv.URL, r1.SessionID, nil)
	}
	check("cached compute not re-run across reruns",
		atomic.LoadInt64(&cacheCalls) == before,
		fmt.Sprintf("compute calls total=%d (unchanged over 3 reruns)", before))
	st.CacheClear()
	run(srv.URL, r1.SessionID, nil)
	check("CacheClear forces recomputation",
		atomic.LoadInt64(&cacheCalls) == before+1,
		fmt.Sprintf("compute calls total=%d", atomic.LoadInt64(&cacheCalls)))

	// --- 10. Session isolation --------------------------------------------
	section("10. session isolation")
	other := run(srv.URL, "", nil)
	check("fresh session gets a new id", other.SessionID != r1.SessionID, "distinct ids")
	check("fresh session has default widget values",
		prop(findKey(other.Tree, "region"), "value") == "EMEA",
		fmt.Sprint(prop(findKey(other.Tree, "region"), "value")))
	check("fresh session run counter is 1",
		prop(find(other.Tree, "metric"), "value") == "1",
		fmt.Sprint(prop(find(other.Tree, "metric"), "value")))

	// --- 11. File upload endpoint -----------------------------------------
	section("11. upload endpoint")
	// HOLE: the app above cannot use FileUploader in a way this driver can
	// verify end to end without duplicating the multipart wire format, which
	// is also undocumented in the README. The endpoint itself is reachable:
	resp, err := http.Post(srv.URL+"/api/upload", "application/json", strings.NewReader("{}"))
	must(err)
	resp.Body.Close()
	check("upload rejects non-multipart bodies", resp.StatusCode == http.StatusBadRequest,
		fmt.Sprintf("status=%d", resp.StatusCode))

	// --- 12. Embedded frontend --------------------------------------------
	section("12. embedded frontend assets")
	for _, p := range []string{"/", "/app.js", "/style.css"} {
		res, err := http.Get(srv.URL + p)
		must(err)
		b, _ := io.ReadAll(res.Body)
		res.Body.Close()
		check("serves "+p, res.StatusCode == 200 && len(b) > 0,
			fmt.Sprintf("status=%d ctype=%s bytes=%d", res.StatusCode, res.Header.Get("Content-Type"), len(b)))
	}

	section("result")
	if failed {
		fmt.Println("  SOME CHECKS FAILED")
		os.Exit(1)
	}
	fmt.Println("  all checks passed; server shut down")
}

func findAllAlerts(root *st.Element) []*st.Element {
	var out []*st.Element
	if root == nil {
		return out
	}
	if root.Type == "alert" {
		out = append(out, root)
	}
	for _, c := range root.Children {
		out = append(out, findAllAlerts(c)...)
	}
	return out
}

// hasFinalText reports whether the trailing "Reached end of app." text element
// is present, which distinguishes a complete run from one halted by Stop().
func hasFinalText(root *st.Element) bool {
	if root == nil {
		return false
	}
	if root.Type == "text" && fmt.Sprint(prop(root, "text")) == "Reached end of app." {
		return true
	}
	for _, c := range root.Children {
		if hasFinalText(c) {
			return true
		}
	}
	return false
}
