// Shared metadata helpers for the App Router routes.
//
// Two deployments serve the same 90 pages — Vercel at the domain root and the
// GitHub Pages export under /go — so both must point their canonical at the one
// origin below, otherwise the two copies compete as duplicates of each other.
// The origin is also what `metadataBase` resolves every relative metadata URL
// against (canonical, og:url, and any opengraph-image the file convention
// emits). Overridable per deployment through NEXT_PUBLIC_SITE_URL: a build-time
// public var, so the static export bakes in whatever the exporting build got.
import type { Metadata } from 'next';

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://go-malcolms-projects-18e573c3.vercel.app';

export const SITE_NAME = 'malcolmston/go';

export const SITE_DESCRIPTION = 'The Node.js ecosystem, reimagined in Go.';

// The route the site-wide card image is served from (app/opengraph-image.tsx),
// and the alt text that file declares. Relative, so metadataBase absolutises it.
export const SITE_IMAGE = '/opengraph-image';
export const SITE_IMAGE_ALT = 'malcolmston/go — the Node.js ecosystem, reimagined in Go';

/**
 * Per-route Open Graph, Twitter card and canonical, built from the title and
 * description a page has already computed for its <title>/<meta description>.
 *
 * Every field is spelled out rather than inherited because Next merges metadata
 * shallowly per top-level key: a route that declares `openGraph` REPLACES the
 * layout's `openGraph` wholesale, so the type/siteName/locale have to be
 * restated here (once, in this helper) instead of being picked up from the root.
 *
 * `path` is a site-root-relative path ('/parity', '/lib/express'); metadataBase
 * turns it into the absolute canonical and og:url.
 *
 * `image` defaults to the site-wide card generated by app/opengraph-image.tsx,
 * because that inherited image is one of the things a declared `openGraph`
 * replaces. A route whose OWN segment has an opengraph-image file (as
 * /lib/[id] does) passes `image: null`: that image is attached by the file
 * convention and must not be shadowed by a URL string here.
 */
export function pageMetadata({
  title,
  description,
  path,
  image = SITE_IMAGE,
}: {
  title: string;
  description: string;
  path: string;
  image?: string | null;
}): Metadata {
  const images = image ? [{ url: image, width: 1200, height: 630, alt: SITE_IMAGE_ALT }] : undefined;
  // The og:title carries the same suffix the browser tab shows, because the
  // layout's title.template only applies to `title`, never to og:title.
  const ogTitle = `${title} · ${SITE_NAME}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      siteName: SITE_NAME,
      locale: 'en_US',
      url: path,
      title: ogTitle,
      description,
      ...(images ? { images } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle,
      description,
      ...(images ? { images } : {}),
    },
  };
}
