// Package parity drives the upstream JavaScript implementation (yaml@2.6.1) and
// the Go port (github.com/malcolmston/yaml) over the same cases and compares
// their answers.
//
// The corpus comes from yaml/yaml-test-suite, which is a *conformance corpus*
// rather than a library: each of its tests supplies an input document, whether
// that document must fail to parse, and sometimes the JSON value it must load
// as. So this suite reports two different numbers:
//
//   - parity: do the two implementations answer the same way? (the oracle is
//     the JavaScript library, exactly as for every other port here)
//   - conformance: does each implementation answer the way the test suite says?
//     split into accept-cases and must-fail cases.
//
// Neither number is hand-written: cases/*.json is generated by
// node/gen-cases.mjs from a pinned suite revision.
//
// Run with:
//
//	GOWORK=off go test ./parity/yaml/
//
// The suite skips (never fails) when Node, the pinned upstream install, or the
// generated corpus is unavailable, so a Go-only checkout stays green.
package parity

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"
)

const (
	// nodePin is the reference implementation used as the oracle.
	nodePin = "yaml@2.6.1"
	// suiteRev is the yaml/yaml-test-suite commit the corpus was generated from
	// (branch main, where every test lives as a YAML file under src/).
	suiteRev = "da267a5c4782e7361e82889e76c0dc7df0e1e870"

	upstreamPin = nodePin + "+yaml-test-suite@" + suiteRev
	caseTimeout = 20 * time.Second
)

// ---------------------------------------------------------------- case files

type caseSpec struct {
	ID         string            `json:"id"`
	Fn         string            `json:"fn"`
	Args       []json.RawMessage `json:"args"`
	UpstreamFn string            `json:"upstreamFn,omitempty"`
	GoFn       string            `json:"goFn,omitempty"`
	Note       string            `json:"note,omitempty"`
	Deviation  string            `json:"deviation,omitempty"`

	// Fields below carry the test suite's own expectation, which is what makes
	// the conformance score possible. They are absent on the hand-written
	// groups, which have no suite opinion to compare against.

	// Expect is "accept" or "fail": whether the suite says this document is
	// well-formed YAML. Only meaningful for fn == "parse".
	Expect string `json:"expect,omitempty"`
	// Suite is the suite's test id (e.g. "229Q" or "ZYU8-03").
	Suite string `json:"suite,omitempty"`
	// SuiteTags are the suite's own tags for the test ("flow", "anchor", ...),
	// which is how COVERAGE.md groups the corpus into sections.
	SuiteTags []string `json:"suiteTags,omitempty"`
	// SuiteJSON is the JSON text the suite says the document must load as. A
	// multi-document stream gives several concatenated JSON values.
	SuiteJSON string `json:"suiteJSON,omitempty"`

	group string
}

type caseFile struct {
	Group    string     `json:"group"`
	Upstream string     `json:"upstream"`
	Cases    []caseSpec `json:"cases"`
}

func loadCases(t *testing.T, dir string) []caseSpec {
	t.Helper()

	paths, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		t.Fatalf("glob cases: %v", err)
	}
	sort.Strings(paths)
	if len(paths) == 0 {
		t.Skipf("no case files in %s; run `node gen-cases.mjs <yaml-test-suite>` in node/", dir)
	}

	var all []caseSpec
	seen := map[string]string{}
	for _, path := range paths {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		var cf caseFile
		if err := json.Unmarshal(raw, &cf); err != nil {
			t.Fatalf("parse %s: %v", path, err)
		}
		if cf.Upstream != upstreamPin {
			t.Fatalf("%s pins upstream %q, want %q", path, cf.Upstream, upstreamPin)
		}
		for _, c := range cf.Cases {
			if prev, dup := seen[c.ID]; dup {
				t.Fatalf("duplicate case id %q (in %s and %s)", c.ID, prev, path)
			}
			seen[c.ID] = path
			c.group = cf.Group
			all = append(all, c)
		}
	}
	return all
}

// ------------------------------------------------------------------- runners

type reply struct {
	ID    string          `json:"id"`
	OK    bool            `json:"ok"`
	Value json.RawMessage `json:"value"`
	// Detail is free-form and never compared: a runner uses it to show, for
	// example, the emitted text that failed to re-parse.
	Detail json.RawMessage `json:"detail"`
	Error  string          `json:"error"`
}

// runner is one long-lived subprocess speaking JSON Lines. Requests are
// serialised; a case that times out marks the runner broken so the remaining
// cases fail fast instead of hanging the suite.
type runner struct {
	name   string
	cmd    *exec.Cmd
	stdin  io.WriteCloser
	lines  chan string
	readEr chan error

	mu     sync.Mutex
	broken string
}

func startRunner(t *testing.T, name string, cmd *exec.Cmd) *runner {
	t.Helper()

	stdin, err := cmd.StdinPipe()
	if err != nil {
		t.Fatalf("%s: stdin pipe: %v", name, err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		t.Fatalf("%s: stdout pipe: %v", name, err)
	}
	var stderr strings.Builder
	cmd.Stderr = &stderr

	if err := cmd.Start(); err != nil {
		t.Fatalf("%s: start: %v", name, err)
	}

	r := &runner{
		name:   name,
		cmd:    cmd,
		stdin:  stdin,
		lines:  make(chan string, 64),
		readEr: make(chan error, 1),
	}

	go func() {
		sc := bufio.NewScanner(stdout)
		sc.Buffer(make([]byte, 0, 64*1024), 64*1024*1024)
		for sc.Scan() {
			r.lines <- sc.Text()
		}
		r.readEr <- sc.Err()
		close(r.lines)
	}()

	t.Cleanup(func() {
		_ = stdin.Close()
		done := make(chan struct{})
		go func() { _ = cmd.Wait(); close(done) }()
		select {
		case <-done:
		case <-time.After(5 * time.Second):
			_ = cmd.Process.Kill()
		}
		if s := stderr.String(); strings.TrimSpace(s) != "" {
			t.Logf("%s stderr:\n%s", name, s)
		}
	})

	return r
}

func (r *runner) call(c caseSpec) reply {
	r.mu.Lock()
	defer r.mu.Unlock()

	if r.broken != "" {
		return reply{ID: c.ID, OK: false, Error: "runner unusable: " + r.broken}
	}

	req := map[string]any{"id": c.ID, "fn": c.Fn, "args": c.Args}
	enc, err := json.Marshal(req)
	if err != nil {
		return reply{ID: c.ID, OK: false, Error: "encode request: " + err.Error()}
	}
	if _, err := r.stdin.Write(append(enc, '\n')); err != nil {
		r.broken = "write: " + err.Error()
		return reply{ID: c.ID, OK: false, Error: r.broken}
	}

	select {
	case line, open := <-r.lines:
		if !open {
			r.broken = "runner closed stdout"
			return reply{ID: c.ID, OK: false, Error: r.broken}
		}
		var rep reply
		if err := json.Unmarshal([]byte(line), &rep); err != nil {
			r.broken = "unparseable reply: " + err.Error()
			return reply{ID: c.ID, OK: false, Error: r.broken}
		}
		if rep.ID != c.ID {
			r.broken = fmt.Sprintf("out of sync: got reply for %q while asking %q", rep.ID, c.ID)
			return reply{ID: c.ID, OK: false, Error: r.broken}
		}
		return rep
	case <-time.After(caseTimeout):
		r.broken = fmt.Sprintf("timed out after %s on case %q", caseTimeout, c.ID)
		return reply{ID: c.ID, OK: false, Error: r.broken}
	}
}

// ------------------------------------------------------------------ compare

// decode turns a JSON value into the normalised form used for comparison: all
// numbers become float64, so 1 and 1.0 compare equal.
func decode(raw json.RawMessage) (any, error) {
	if len(raw) == 0 {
		return nil, nil
	}
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// show renders a value so escape sequences stay readable in test output, and
// truncates it: a suite document can decode to a large tree.
func show(raw json.RawMessage) string {
	v, err := decode(raw)
	if err != nil {
		return fmt.Sprintf("<unparseable %s>", raw)
	}
	var s string
	if str, ok := v.(string); ok {
		s = fmt.Sprintf("%q", str)
	} else if out, err := json.Marshal(v); err == nil {
		s = string(out)
	} else {
		s = fmt.Sprint(v)
	}
	if len(s) > 600 {
		s = s[:600] + "...(truncated)"
	}
	return s
}

// ---------------------------------------------------- the suite's own answer

// suiteValues decodes the suite's expected JSON. A multi-document stream is
// written as several concatenated JSON values, so they are read in sequence.
func suiteValues(text string) ([]any, error) {
	dec := json.NewDecoder(strings.NewReader(text))
	var out []any
	for {
		var v any
		err := dec.Decode(&v)
		if errors.Is(err, io.EOF) {
			return out, nil
		}
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
}

// conforms reports whether one runner's answer agrees with the test suite.
func conforms(c caseSpec, rep reply) bool {
	switch {
	case c.SuiteJSON != "":
		if !rep.OK {
			return false
		}
		want, err := suiteValues(c.SuiteJSON)
		if err != nil {
			return false
		}
		got, err := decode(rep.Value)
		if err != nil {
			return false
		}
		return reflect.DeepEqual(canon(got), canon(want))
	case c.Expect == "accept":
		return rep.OK
	case c.Expect == "fail":
		return !rep.OK
	}
	return false
}

// canon strips the differences between the runners' normalised values and the
// suite's plain JSON that are artefacts of the harness rather than of either
// implementation:
//
//   - {"!!binary": hex} / {"!!timestamp": iso}: the runners tag these so that a
//     dropped tag cannot pass unnoticed, but the suite's JSON has no such
//     notion, so the wrapper is removed before scoring conformance.
//   - a whole-number float is written as an integer, so 1 and 1.0 agree.
func canon(v any) any {
	switch t := v.(type) {
	case map[string]any:
		if len(t) == 1 {
			for _, k := range []string{"!!binary", "!!timestamp"} {
				if inner, ok := t[k]; ok {
					return canon(inner)
				}
			}
		}
		out := make(map[string]any, len(t))
		for k, val := range t {
			out[k] = canon(val)
		}
		return out
	case []any:
		out := make([]any, len(t))
		for i, val := range t {
			out[i] = canon(val)
		}
		return out
	case float64:
		if t == math.Trunc(t) && !math.IsInf(t, 0) && math.Abs(t) < 1e15 {
			return fmt.Sprintf("%d", int64(t))
		}
		return t
	}
	return v
}

// ---------------------------------------------------------------- the score

type groupScore struct {
	Cases      int `json:"cases"`
	Match      int `json:"match"`
	Mismatch   int `json:"mismatch"`
	Deviations int `json:"deviations"`
}

// conformanceScore is one side measured against the test suite rather than
// against the other side.
type conformanceScore struct {
	Cases   int     `json:"cases"`
	Node    int     `json:"node"`
	Go      int     `json:"go"`
	NodePct float64 `json:"nodePercent"`
	GoPct   float64 `json:"goPercent"`
	// The suite ids each side answers differently from the suite, so the score
	// can be audited case by case.
	NodeFails []string `json:"nodeFails"`
	GoFails   []string `json:"goFails"`
}

type score struct {
	Library       string                      `json:"library"`
	Upstream      string                      `json:"upstream"`
	SuiteRevision string                      `json:"suiteRevision"`
	GoModule      string                      `json:"goModule"`
	Cases         int                         `json:"cases"`
	Match         int                         `json:"match"`
	Mismatch      int                         `json:"mismatch"`
	Deviations    int                         `json:"deviations"`
	ParityPercent float64                     `json:"parityPercent"`
	Groups        map[string]groupScore       `json:"groups"`
	Conformance   map[string]conformanceScore `json:"conformance"`
	Mismatches    []string                    `json:"mismatches"`
}

var modLine = regexp.MustCompile(`github\.com/malcolmston/yaml\s+(v\S+)`)

func goModuleVersion() string {
	raw, err := os.ReadFile("go.mod")
	if err != nil {
		return "unknown"
	}
	if m := modLine.FindSubmatch(raw); m != nil {
		return "github.com/malcolmston/yaml " + string(m[1])
	}
	return "unknown"
}

// ------------------------------------------------------------------- harness

func TestParity(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node not found in PATH; skipping cross-language parity")
	}

	if _, err := os.Stat(filepath.Join("node", "node_modules", "yaml", "package.json")); err != nil {
		install := exec.Command("npm", "install", "--no-audit", "--no-fund")
		install.Dir = "node"
		if out, ierr := install.CombinedOutput(); ierr != nil {
			t.Skipf("upstream %s not installed and `npm install` failed: %v\n%s", nodePin, ierr, out)
		}
	}
	assertUpstreamVersion(t)

	cases := loadCases(t, "cases")

	bin := filepath.Join(t.TempDir(), "gorunner")
	build := exec.Command("go", "build", "-o", bin, "./go")
	build.Env = append(os.Environ(), "GOWORK=off")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build Go runner: %v\n%s", err, out)
	}

	nodeCmd := exec.Command(node, "run.mjs")
	nodeCmd.Dir = "node"
	up := startRunner(t, "node", nodeCmd)

	goCmd := exec.Command(bin)
	goCmd.Env = append(os.Environ(), "GOWORK=off")
	gor := startRunner(t, "go", goCmd)

	sc := score{
		Library:       "yaml",
		Upstream:      upstreamPin,
		SuiteRevision: suiteRev,
		GoModule:      goModuleVersion(),
		Cases:         len(cases),
		Groups:        map[string]groupScore{},
		Conformance:   map[string]conformanceScore{},
		Mismatches:    []string{},
	}

	for _, c := range cases {
		upRep := up.call(c)
		goRep := gor.call(c)

		ran, ok := compare(t, c, upRep, goRep)
		if !ran {
			// Subtest filtered out by -run: do not score it.
			continue
		}

		g := sc.Groups[c.group]
		g.Cases++
		switch {
		case c.Deviation != "":
			g.Deviations++
			sc.Deviations++
		case ok:
			g.Match++
			sc.Match++
		default:
			g.Mismatch++
			sc.Mismatch++
			sc.Mismatches = append(sc.Mismatches, c.ID)
		}
		sc.Groups[c.group] = g

		// Conformance is scored per side against the suite, independently of
		// whether the two sides agree with each other.
		if bucket := conformanceBucket(c); bucket != "" {
			b := sc.Conformance[bucket]
			b.Cases++
			if conforms(c, upRep) {
				b.Node++
			} else {
				b.NodeFails = append(b.NodeFails, c.Suite)
			}
			if conforms(c, goRep) {
				b.Go++
			} else {
				b.GoFails = append(b.GoFails, c.Suite)
			}
			sc.Conformance[bucket] = b
		}
	}

	compared := sc.Match + sc.Mismatch
	if compared > 0 {
		sc.ParityPercent = float64(sc.Match) * 100 / float64(compared)
	}
	for k, b := range sc.Conformance {
		if b.Cases > 0 {
			b.NodePct = float64(b.Node) * 100 / float64(b.Cases)
			b.GoPct = float64(b.Go) * 100 / float64(b.Cases)
		}
		sc.Conformance[k] = b
	}

	t.Logf("parity: %d/%d cases match (%.2f%%), %d deviations",
		sc.Match, compared, sc.ParityPercent, sc.Deviations)
	for _, k := range sortedKeys(sc.Conformance) {
		b := sc.Conformance[k]
		t.Logf("conformance %-14s node %d/%d (%.2f%%)  go %d/%d (%.2f%%)",
			k, b.Node, b.Cases, b.NodePct, b.Go, b.Cases, b.GoPct)
	}

	// A -run filter skips subtests, which would leave a misleading score on
	// disk, so only a complete pass is allowed to rewrite parity.json.
	if scored := compared + sc.Deviations; scored != len(cases) {
		t.Logf("partial run (%d of %d cases scored): leaving parity.json alone",
			scored, len(cases))
		return
	}
	writeScore(t, sc)
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// conformanceBucket names the conformance number a case contributes to, or ""
// when the suite has no expectation for it (the hand-written groups).
func conformanceBucket(c caseSpec) string {
	switch {
	case c.SuiteJSON != "":
		return "suite-json"
	case c.Expect == "accept" && c.Fn == "parse":
		return "suite-accept"
	case c.Expect == "fail" && c.Fn == "parse":
		return "suite-must-fail"
	}
	return ""
}

// compare runs one case as a subtest. It reports whether the subtest actually
// ran (a -run filter can skip it) and whether the two sides agree.
func compare(t *testing.T, c caseSpec, upRep, goRep reply) (ran, agreed bool) {
	t.Run(c.ID, func(t *testing.T) {
		ran = true
		// The message is assembled before it reaches t.Errorf: case notes and
		// emitted YAML routinely contain '%', which must not be read as a
		// format verb.
		fail := func(format string, args ...any) {
			msg := fmt.Sprintf(format, args...)
			if c.Note != "" {
				msg += "\n  case: " + c.Note
			}
			msg += details(upRep, goRep)
			if c.Deviation != "" {
				t.Logf("deviation (%s): %s", c.Deviation, msg)
				return
			}
			t.Error(msg)
		}

		if upRep.OK != goRep.OK {
			fail("ok mismatch: upstream ok=%v (%s), go ok=%v (%s)",
				upRep.OK, describe(upRep), goRep.OK, describe(goRep))
			return
		}
		if !upRep.OK {
			// Both failed: that is parity. Message text is not compared;
			// differences are recorded in COVERAGE.md.
			agreed = true
			return
		}

		upVal, err := decode(upRep.Value)
		if err != nil {
			fail("upstream value is not JSON: %v", err)
			return
		}
		goVal, err := decode(goRep.Value)
		if err != nil {
			fail("go value is not JSON: %v", err)
			return
		}
		if !reflect.DeepEqual(upVal, goVal) {
			fail("value mismatch\n  upstream: %s\n        go: %s", show(upRep.Value), show(goRep.Value))
			return
		}
		agreed = true
	})

	if c.Deviation != "" {
		return ran, ran
	}
	return ran, agreed
}

// details renders each runner's uncompared "detail" object, which is where the
// emitter cases put the text that failed to re-parse.
func details(upRep, goRep reply) string {
	var b strings.Builder
	for _, d := range []struct {
		name string
		raw  json.RawMessage
	}{{"upstream", upRep.Detail}, {"go", goRep.Detail}} {
		if len(d.raw) == 0 || string(d.raw) == "null" {
			continue
		}
		fmt.Fprintf(&b, "\n  %s detail: %s", d.name, show(d.raw))
	}
	return b.String()
}

func describe(r reply) string {
	if r.OK {
		return "value " + show(r.Value)
	}
	return "error " + fmt.Sprintf("%q", r.Error)
}

func writeScore(t *testing.T, sc score) {
	t.Helper()
	sort.Strings(sc.Mismatches)
	enc, err := json.MarshalIndent(sc, "", "  ")
	if err != nil {
		t.Fatalf("encode parity.json: %v", err)
	}
	if err := os.WriteFile("parity.json", append(enc, '\n'), 0o644); err != nil {
		t.Fatalf("write parity.json: %v", err)
	}
}

// assertUpstreamVersion checks the installed oracle matches the pin, so the
// score can never be attributed to the wrong upstream.
func assertUpstreamVersion(t *testing.T) {
	t.Helper()
	want := strings.SplitN(nodePin, "@", 2)[1]

	raw, err := os.ReadFile(filepath.Join("node", "node_modules", "yaml", "package.json"))
	if err != nil {
		t.Skipf("cannot read installed yaml: %v", err)
	}
	var pkg struct{ Version string }
	if err := json.Unmarshal(raw, &pkg); err != nil {
		t.Fatalf("parse installed yaml package.json: %v", err)
	}
	if pkg.Version != want {
		t.Fatalf("installed yaml is %s, cases pin %s", pkg.Version, want)
	}
}
