// Code generated by sampling d3-scale-chromatic v3.1.0 in Node. DO NOT EDIT.

package scalechromatic

import (
	"math"
	"testing"

	"github.com/malcolmston/d3/color"
)

// goldenT are the sample points of [goldenRamps].
var goldenT = []float64{0, 0.05, 0.1, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.7, 0.75, 0.8, 0.9, 0.95, 1}

// goldenRamps records what upstream d3-scale-chromatic v3.1.0 returns at each of
// [goldenT], for every interpolator this package exports, captured by running the
// published bundle under Node against the real d3-color and d3-interpolate.
//
// This is the only evidence in the repository that the interior of a tabulated
// ramp is right. Endpoint and gamut tests cannot see a wrong hex digit in the
// middle of a ColorBrewer scheme; these samples can, because they were produced by
// a different implementation reading the same published tables.
var goldenRamps = map[string]string{
	"Blues":            "f7fbffedf5fce3eef9cfe1f2c3dbeeb5d4e993c3df6daed54b97c92f7ebc2271b41864aa0a4a90083d7e08306b",
	"BrBG":             "5430057041088b540fbc8435cea156debe7bf2e4c0eef1eac3e7e27fc9bf5bb2a839988f0a675f025147003c30",
	"BuGn":             "f7fcfdf0f9fbe8f6f9d5efedc8eae4b7e4da8fd3c168c2a349b17f2f9959228c49157f3c03642900542200441b",
	"BuPu":             "f7fcfdeef6f9e4eef5ccddecbfd3e6b2cae19cb3d58f95c68c74b58952a588409b852d8f730f7161065e4d004b",
	"Cividis":          "0020510029620a326a2b446e3c4d6e4d566d6969707f7c75948f78ada476bbaf71caba6aead156f6dd4cfdea45",
	"Cool":             "6e40aa6849ba6054c84c6edb417de0368ce123abd81ac7c21ddfa330ef8240f37352f6677ff65897f357aff05b",
	"CubehelixDefault": "0000001208171a1530163d4e16534c1f664254792fa07949d07e93cf9cdac7b3edc1caf3d2eeefe8f8f2ffffff",
	"GnBu":             "f7fcf0eef8e8e5f5dfd3eecec9eac6bde5bf9ed9bb7bcbc458b7cd399cc62b8dbf1d7eb70b60a1085092084081",
	"Greens":           "f7fcf5f0f9ece8f6e3d3eecdc6e8bfb7e2b197d49473c3784daf622f984f228b45157f3b03642900542200441b",
	"Greys":            "fffffff9f9f9f2f2f2e2e2e2d8d8d8cececeb4b4b49797977a7a7a5f5f5f5050504040401e1e1e0f0f0f000000",
	"Inferno":          "00000407051b160b39420a6857106e6a176e932667bc3754dd513af37819f98e09fca50af6d746f1ef75fcffa4",
	"Magma":            "00000406051a140e363b0f7051127c641a808c2981b73779de4968f7705cfc8961fe9f6dfecf92fde7a9fcfdbf",
	"OrRd":             "fff7ecfff1defeebcffddcaffdd3a1fdca94fdb07afa8e5df16c49e04530d53121c81d13a704039401007f0000",
	"Oranges":          "fff5ebffefdffee8d3fdd8b3fdcea0fdc28cfda762fb8d3df2701de25609d54b04c441039f33038f2d047f2704",
	"PRGn":             "40004b5b1667732f809a6daaae8abdc1a4cde4d2e6eff0efd6eed1a2d79e80c4815cad652178390e5e2900441b",
	"PiYG":             "8e0152a90f68c0267edd72ade795c3f0b3d6faddedf5f3efe1f2cab6de879bce6480bb474f91253a7b1e276419",
	"Plasma":           "0d08872a059341049d6a00a87e03a88f0da4b12a90cc4778e16462f2844bf89540fca636fcce25f7e425f0f921",
	"PuBu":             "fff7fbf7f1f7efeaf4dbdaebced1e6bfc9e29bb9d972a8cf4394c31a7db60d72ad0667a104528103456d023858",
	"PuBuGn":           "fff7fbf7eff7efe7f2dbd8eaced1e6bec9e298b9d969a8cf4096c019879f0b808b037877016353015544014636",
	"PuOr":             "2d004b411469552d848170ac998ebfb0aad0d7d7e9f3eeeafdddb3f8b664ee9d3ddd841fb25a09994a077f3b08",
	"PuRd":             "f7f4f9f1ecf5eae3f0dcc9e2d5badad0aad2d08ac2dd63aee33890d71c6cc9135cb70b4f8f023a7b002d67001f",
	"Purples":          "fcfbfdf7f5faf1eff6e2e1efd9d8eacecee5b6b5d89e9bc98782bc7363ac6a51a461409b501f8c4710843f007d",
	"Rainbow":          "6e40aa963db3bf3caffe4b83ff5e63ff7847e2b72faff05b52f6671ddfa31ac7c223abd84c6edb6054c86e40aa",
	"RdBu":             "67001f8c0d25ac202fd56050e48268f1a385fbd7c4f2efeecde3ee8fc2dd6bacd04b94c42265a3134b85053061",
	"RdGy":             "67001f8c0d25ac202fd56050e48268f1a385fcd8c5faf4f1dfdfdfb8b8b8a0a0a08686864e4e4e3434341a1a1a",
	"RdPu":             "fff7f3feeeeafde4e1fccfccfcc3c3fbb5bcf993b0f369a3e03e98c01788ad0a8199037c7001745d006f49006a",
	"RdYlBu":           "a50026be1827d4322cf16e43f88d52fcac64fedd90faf8c1dcf1ecabd6e890c2dd75abd04a74b43c55a4313695",
	"RdYlGn":           "a50026be1827d4322cf16e43f88d52fcac63fedd8df9f7aed7ee8ea4d86e85cb6764bc6122964f0e8043006837",
	"Reds":             "fff5f0ffece4fee3d6fdc9b4fcbaa1fcaa8efc8a6bf9694cef4533d92723cb1c1ebb151a970b1380061067000d",
	"Sinebow":          "ff4040f96521e78d0ba7d5037fee1158fc2a18f47200bfbf1872f4582afc7f11eea703d5e70b8df92165ff4040",
	"Spectral":         "9e0142b91f48d13c4bf0704af88e53fcac63fedd8dfbf8b0e0f3a1a9dda289cfa569bda94288b54a6cae5e4fa2",
	"Turbo":            "23171b4636994a58dd2f9df526bce127d7c44df88495fb51dedd32ffa423ff821df65f18ba22089d1000900c00",
	"Viridis":          "4401544713654824754144873b528b355f8d2a788e21918c22a88444bf705ec9627ad151bddf26dfe318fde725",
	"Warm":             "6e40aa813eb0963db3bf3cafd23ea7e4419dfe4b83ff5e63ff7847fb9633efa72fe2b72fc6d63cbae449aff05b",
	"YlGn":             "ffffe5fcfed4f7fcc4e4f4acd7efa3c7e89ba2d88a78c5784eaf632f944e22864515793f03603400532f004529",
	"YlGnBu":           "ffffd9f8fcc9eff9bdd5eeb3c1e7b5a9ddb773c9bd45b4c22897bf2073b22260a9234ea01c3185132670081d58",
	"YlOrBr":           "ffffe5fffcd5fff8c4feeaa1fee18dfed676feba4afb992cee7918d85b0ac94e05b743048f32047a2b05662506",
	"YlOrRd":           "ffffccfff8bafff0a9fee087fed676fec965feab4bfd893cfa5c2eec3023e11e20d31121af0225980026800026",
}

// TestAgainstUpstream compares every interpolator against the recorded output of
// the real d3-scale-chromatic, which is the only check in this package that can
// catch a wrong digit in the middle of a table.
//
// Channels are compared as integers because that is what upstream emits, and a
// one-unit difference is tolerated only when this implementation's unrounded
// value sits within 1e-6 of a rounding boundary. That exception is not slack: the
// B-spline through eleven control points lands on values like exactly 9.5 at
// t = 0.9, and V8 and Go accumulate the same sum in a different order, so one
// side computes 9.4999999999999947 and the other 9.5 and they round apart. Seven
// of 7752 samples in the original comparison were of that kind and no others
// differed at all. Any genuine error in a table or a coefficient misses by far
// more than a unit and is caught here.
func TestAgainstUpstream(t *testing.T) {
	got := Interpolators()
	if len(got) != len(goldenRamps) {
		t.Errorf("package exports %d interpolators, upstream sample has %d", len(got), len(goldenRamps))
	}
	for name, packed := range goldenRamps {
		f, ok := got[name]
		if !ok {
			t.Errorf("upstream has interpolator %q and this package does not", name)
			continue
		}
		want := colors(packed)
		if len(want) != len(goldenT) {
			t.Fatalf("%s: golden row has %d colors, want %d", name, len(want), len(goldenT))
		}
		for i, x := range goldenT {
			c := color.ToRGB(f(x))
			w := color.ToRGB(want[i])
			for j, pair := range [3][2]float64{{c.R, w.R}, {c.G, w.G}, {c.B, w.B}} {
				raw, exp := pair[0], pair[1]
				d := math.Abs(math.Floor(math.Max(0, math.Min(255, raw))+0.5) - exp)
				if d == 0 {
					continue
				}
				if d <= 1 && math.Abs(raw-math.Floor(raw)-0.5) < 1e-6 {
					continue // a rounding tie; see the doc comment
				}
				t.Errorf("Interpolate%s(%g) channel %d = %v, upstream %v", name, x, j, raw, exp)
			}
		}
	}
}
