// Code generated from d3-scale-chromatic v3.1.0. DO NOT EDIT.
//
// The registry tables. Hand-maintaining these alongside the schemes themselves
// would guarantee that one of them eventually goes stale; generating both from
// the same extraction is what keeps Interpolators() and the exported functions in
// agreement.

package scalechromatic

import "github.com/malcolmston/d3/color"

var schemeTable = map[string][]color.Color{
	"category10":   SchemeCategory10,
	"accent":       SchemeAccent,
	"dark2":        SchemeDark2,
	"paired":       SchemePaired,
	"pastel1":      SchemePastel1,
	"pastel2":      SchemePastel2,
	"set1":         SchemeSet1,
	"set2":         SchemeSet2,
	"set3":         SchemeSet3,
	"tableau10":    SchemeTableau10,
	"observable10": SchemeObservable10,
}

var familyTable = map[string]Family{
	"brbg":     SchemeBrBG,
	"prgn":     SchemePRGn,
	"piyg":     SchemePiYG,
	"puor":     SchemePuOr,
	"rdbu":     SchemeRdBu,
	"rdgy":     SchemeRdGy,
	"rdylbu":   SchemeRdYlBu,
	"rdylgn":   SchemeRdYlGn,
	"spectral": SchemeSpectral,
	"bugn":     SchemeBuGn,
	"bupu":     SchemeBuPu,
	"gnbu":     SchemeGnBu,
	"orrd":     SchemeOrRd,
	"pubugn":   SchemePuBuGn,
	"pubu":     SchemePuBu,
	"purd":     SchemePuRd,
	"rdpu":     SchemeRdPu,
	"ylgnbu":   SchemeYlGnBu,
	"ylgn":     SchemeYlGn,
	"ylorbr":   SchemeYlOrBr,
	"ylorrd":   SchemeYlOrRd,
	"blues":    SchemeBlues,
	"greens":   SchemeGreens,
	"greys":    SchemeGreys,
	"purples":  SchemePurples,
	"reds":     SchemeReds,
	"oranges":  SchemeOranges,
}

var interpolatorTable = map[string]func(float64) color.Color{
	"brbg":             InterpolateBrBG,
	"prgn":             InterpolatePRGn,
	"piyg":             InterpolatePiYG,
	"puor":             InterpolatePuOr,
	"rdbu":             InterpolateRdBu,
	"rdgy":             InterpolateRdGy,
	"rdylbu":           InterpolateRdYlBu,
	"rdylgn":           InterpolateRdYlGn,
	"spectral":         InterpolateSpectral,
	"bugn":             InterpolateBuGn,
	"bupu":             InterpolateBuPu,
	"gnbu":             InterpolateGnBu,
	"orrd":             InterpolateOrRd,
	"pubugn":           InterpolatePuBuGn,
	"pubu":             InterpolatePuBu,
	"purd":             InterpolatePuRd,
	"rdpu":             InterpolateRdPu,
	"ylgnbu":           InterpolateYlGnBu,
	"ylgn":             InterpolateYlGn,
	"ylorbr":           InterpolateYlOrBr,
	"ylorrd":           InterpolateYlOrRd,
	"blues":            InterpolateBlues,
	"greens":           InterpolateGreens,
	"greys":            InterpolateGreys,
	"purples":          InterpolatePurples,
	"reds":             InterpolateReds,
	"oranges":          InterpolateOranges,
	"viridis":          InterpolateViridis,
	"magma":            InterpolateMagma,
	"inferno":          InterpolateInferno,
	"plasma":           InterpolatePlasma,
	"cividis":          InterpolateCividis,
	"turbo":            InterpolateTurbo,
	"cubehelixdefault": InterpolateCubehelixDefault,
	"warm":             InterpolateWarm,
	"cool":             InterpolateCool,
	"rainbow":          InterpolateRainbow,
	"sinebow":          InterpolateSinebow,
}

// canonicalNames maps the lowercased lookup key back to the spelling this
// package exports, so that a picker built from a registry can label itself the
// way the documentation does.
var canonicalNames = map[string]string{
	"accent":           "Accent",
	"blues":            "Blues",
	"brbg":             "BrBG",
	"bugn":             "BuGn",
	"bupu":             "BuPu",
	"category10":       "Category10",
	"cividis":          "Cividis",
	"cool":             "Cool",
	"cubehelixdefault": "CubehelixDefault",
	"dark2":            "Dark2",
	"gnbu":             "GnBu",
	"greens":           "Greens",
	"greys":            "Greys",
	"inferno":          "Inferno",
	"magma":            "Magma",
	"observable10":     "Observable10",
	"orrd":             "OrRd",
	"oranges":          "Oranges",
	"prgn":             "PRGn",
	"paired":           "Paired",
	"pastel1":          "Pastel1",
	"pastel2":          "Pastel2",
	"piyg":             "PiYG",
	"plasma":           "Plasma",
	"pubu":             "PuBu",
	"pubugn":           "PuBuGn",
	"puor":             "PuOr",
	"purd":             "PuRd",
	"purples":          "Purples",
	"rainbow":          "Rainbow",
	"rdbu":             "RdBu",
	"rdgy":             "RdGy",
	"rdpu":             "RdPu",
	"rdylbu":           "RdYlBu",
	"rdylgn":           "RdYlGn",
	"reds":             "Reds",
	"set1":             "Set1",
	"set2":             "Set2",
	"set3":             "Set3",
	"sinebow":          "Sinebow",
	"spectral":         "Spectral",
	"tableau10":        "Tableau10",
	"turbo":            "Turbo",
	"viridis":          "Viridis",
	"warm":             "Warm",
	"ylgn":             "YlGn",
	"ylgnbu":           "YlGnBu",
	"ylorbr":           "YlOrBr",
	"ylorrd":           "YlOrRd",
}
