'use strict';
// gen-tables.js regenerates the Go reference tables in
//   express/htmlentities/tables.go
// straight out of the installed html-entities package, so the port's data is
// mechanically derived from the oracle rather than transcribed.
//
//   node gen-tables.js > ../../../../../express/htmlentities/tables.go
//
// It emits, for each of the three levels html-entities defines (xml, html4,
// html5 — "all" is an alias for html5):
//   * entities:   entity spelling (with & and optional ;) -> replacement text
//   * characters: character -> preferred named entity
// plus numericUnicodeMap (the Windows-1252 fix-ups the HTML spec mandates for
// numeric references in the 0x80..0x9F range) and the three "body scope"
// matching regexes, which are already RE2-compatible.

const nr = require('./node_modules/html-entities/dist/commonjs/named-references.js');
const num = require('./node_modules/html-entities/dist/commonjs/numeric-unicode-map.js');
const pkg = require('./node_modules/html-entities/package.json');

function q(s) {
  // Go and JSON agree on string escapes for everything that appears here, and
  // JSON.stringify escapes control characters, so this is a valid Go literal.
  return JSON.stringify(s);
}

function emitMap(name, comment, obj) {
  const keys = Object.keys(obj).sort();
  out.push(`// ${comment}`);
  out.push(`var ${name} = map[string]string{`);
  for (const k of keys) out.push(`\t${q(k)}: ${q(obj[k])},`);
  out.push('}');
  out.push('');
}

const out = [];
out.push('// Code generated by parity/express/nested/htmlentities/node/gen-tables.js. DO NOT EDIT.');
out.push(`// Source: html-entities@${pkg.version} (dist/commonjs/named-references.js,`);
out.push('// dist/commonjs/numeric-unicode-map.js). Regenerate with:');
out.push('//');
out.push('//\tcd parity/express/nested/htmlentities/node && node gen-tables.js > ../../../../../express/htmlentities/tables.go');
out.push('');
out.push('package htmlentities');
out.push('');

for (const level of ['xml', 'html4', 'html5']) {
  const cap = {xml: 'XML', html4: 'HTML4', html5: 'HTML5'}[level];
  emitMap(
    `entities${cap}`,
    `entities${cap} maps every ${level} entity spelling — including the legacy forms with no trailing semicolon — to its replacement text.`,
    nr.namedReferences[level].entities
  );
  emitMap(
    `characters${cap}`,
    `characters${cap} maps a character to the named ${level} entity Encode prefers for it.`,
    nr.namedReferences[level].characters
  );
}

out.push('// numericUnicodeMap holds the code points a numeric character reference must be');
out.push('// remapped to instead of taken literally: the C1 range that HTML reinterprets as');
out.push('// Windows-1252, plus NUL, which becomes the replacement character.');
out.push('var numericUnicodeMap = map[int]rune{');
for (const k of Object.keys(num.numericUnicodeMap).map(Number).sort((a, b) => a - b)) {
  out.push(`\t${k}: ${num.numericUnicodeMap[k]},`);
}
out.push('}');
out.push('');

out.push('// bodyPattern holds, per level, the pattern that finds an entity reference in');
out.push('// "body" decoding scope, where a trailing semicolon is optional for the legacy');
out.push('// named references only. These are the upstream bodyRegExps sources verbatim;');
out.push('// they use nothing outside RE2, and Go alternation is leftmost-first like');
out.push("// JavaScript's, so the same alternative wins.");
out.push('var bodyPattern = map[string]string{');
for (const level of ['xml', 'html4', 'html5']) {
  out.push(`\t${q(level)}: ${q(nr.bodyRegExps[level].source)},`);
}
out.push('}');

process.stdout.write(out.join('\n') + '\n');
