#!/usr/bin/env node
// Generates the CommonMark conformance case files from the vendored, pinned
// spec.json.
//
//	node gen-cases.mjs
//
// `cases/spec.json` is the machine-readable conformance suite shipped by
// commonmark/commonmark-spec for CommonMark 0.31.2 (fetched verbatim from
// https://spec.commonmark.org/0.31.2/spec.json). Each entry is a
// (markdown, html, section, example) tuple, so the *expected HTML is not
// hand-written* -- it is the specification's own oracle, which is why these
// cases carry a `specHTML` field that the harness compares against alongside
// the upstream commonmark.js answer.
//
// One case file per spec section, named `spec-NN-<slug>.json` in section order.
// Group names are the spec's own section titles and case ids are the spec's own
// example numbers, so a failure points straight at a line of the spec.
//
// The hand-written groups (security.json, options.json, api.json) are NOT
// generated and are never touched by this script.

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const casesDir = path.join(here, 'cases');
const specPath = path.join(casesDir, 'spec.json');

const SPEC_VERSION = '0.31.2';
const UPSTREAM_PIN = 'commonmark@0.31.2';

const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));

function slug(section) {
	return section
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-|-$/g, '');
}

// Section order is the order sections first appear in the spec.
const order = [];
const bySection = new Map();
for (const entry of spec) {
	if (!bySection.has(entry.section)) {
		bySection.set(entry.section, []);
		order.push(entry.section);
	}

	bySection.get(entry.section).push(entry);
}

// Remove previously generated files so a shrinking spec cannot leave stale
// cases behind. Only `spec-*.json` is generated; everything else is hand-written.
for (const name of fs.readdirSync(casesDir)) {
	if (/^spec-\d+-.*\.json$/.test(name)) {
		fs.unlinkSync(path.join(casesDir, name));
	}
}

let written = 0;
let total = 0;
order.forEach((section, index) => {
	const entries = bySection.get(section);
	const file = {
		group: section,
		upstream: UPSTREAM_PIN,
		specVersion: SPEC_VERSION,
		source: 'cases/spec.json (CommonMark 0.31.2 spec.json), generated by gen-cases.mjs',
		cases: entries.map(entry => ({
			id: `ex-${String(entry.example).padStart(3, '0')}`,
			fn: 'render',
			args: [entry.markdown],
			specHTML: entry.html,
			specLines: `${entry.start_line}-${entry.end_line}`,
			upstreamFn: 'new commonmark.HtmlRenderer().render(new commonmark.Parser().parse(src))',
			goFn: 'markdown.Render',
		})),
	};

	const name = `spec-${String(index + 1).padStart(2, '0')}-${slug(section)}.json`;
	fs.writeFileSync(path.join(casesDir, name), JSON.stringify(file, null, 2) + '\n');
	written++;
	total += entries.length;
});

process.stderr.write(`wrote ${written} case files, ${total} spec examples (CommonMark ${SPEC_VERSION})\n`);
