package rsccompile

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// Options configure code generation.
type Options struct {
	// Package is the Go package the declarations are generated into.
	Package string

	// RSCPath is the URL the Go server serves the Flight payload from.
	RSCPath string

	// MountID is the id of the element the client mounts into.
	MountID string

	// EntryURL is the URL the generated browser entry is served at.
	EntryURL string

	// ReactVersion pins the React the browser loads. It must match the version
	// the payload was verified against, because the wire format is coupled to
	// it — a mismatch here is exactly the failure the pin exists to prevent.
	ReactVersion string

	// ESMHost serves React to the browser as ES modules. Defaulting to a CDN
	// keeps a project free of a JavaScript toolchain; point it at a local copy
	// to remove the third-party dependency.
	ESMHost string
}

// withDefaults fills in the values a caller left blank.
func (o Options) withDefaults() Options {
	if o.Package == "" {
		o.Package = "app"
	}
	if o.RSCPath == "" {
		o.RSCPath = "/rsc"
	}
	if o.MountID == "" {
		o.MountID = "root"
	}
	if o.EntryURL == "" {
		o.EntryURL = "/rsc/entry.js"
	}
	if o.ReactVersion == "" {
		o.ReactVersion = "19.2.8"
	}
	if o.ESMHost == "" {
		o.ESMHost = "https://esm.sh"
	}
	return o
}

// ImportMap returns the browser import map: the three specifiers the entry and
// the client components resolve.
//
// Client components import "react" by bare specifier, exactly as they would in
// a bundled app, so the same source file works either way.
func (o Options) ImportMap() map[string]any {
	o = o.withDefaults()
	host := strings.TrimSuffix(o.ESMHost, "/")
	v := o.ReactVersion
	return map[string]any{
		"imports": map[string]string{
			"react":      fmt.Sprintf("%s/react@%s", host, v),
			"react/":     fmt.Sprintf("%s/react@%s/", host, v),
			"react-dom":  fmt.Sprintf("%s/react-dom@%s", host, v),
			"react-dom/": fmt.Sprintf("%s/react-dom@%s/", host, v),
			"react-server-dom-webpack/client.browser": fmt.Sprintf("%s/react-server-dom-webpack@%s/client.browser", host, v),
		},
	}
}

// GenerateGo renders the Go declarations for the discovered client components.
func GenerateGo(exports []Export, opts Options) (string, error) {
	opts = opts.withDefaults()

	importMap, err := json.Marshal(opts.ImportMap())
	if err != nil {
		return "", err
	}

	data := struct {
		Options
		Exports   []Export
		ImportMap string
	}{opts, exports, string(importMap)}

	var buf bytes.Buffer
	if err := goTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("rsccompile: rendering Go declarations: %w", err)
	}

	// Formatting the output rather than trusting the template means a template
	// mistake surfaces here, as a parse error, instead of as badly formatted
	// code committed to someone's repository.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("rsccompile: generated Go did not parse: %w\n%s", err, buf.String())
	}
	return string(formatted), nil
}

// GenerateEntry renders the browser entry — the init script that fetches the
// payload the Go server produced and mounts it.
func GenerateEntry(opts Options) (string, error) {
	opts = opts.withDefaults()
	var buf bytes.Buffer
	if err := entryTemplate.Execute(&buf, opts); err != nil {
		return "", fmt.Errorf("rsccompile: rendering the browser entry: %w", err)
	}
	return buf.String(), nil
}

var goTemplate = template.Must(template.New("go").Parse(`// Code generated by ` + "`react rsc`" + `. DO NOT EDIT.
//
// Each declaration below is a reference to a JavaScript module marked
// "use client". The Go server never runs that code — it sends a reference, and
// the browser loads the real module and renders it.

package {{.Package}}

import (
	"github.com/malcolmston/react"
	"github.com/malcolmston/react/rsc"
)
{{range .Exports}}
// {{.GoName}} is the {{if eq .Name "default"}}default export{{else}}{{.Name}} export{{end}} of {{.Module.Rel}}.
var {{.GoName}} = rsc.Client({{printf "%q" .Module.URL}}, {{printf "%q" .Name}}, {{printf "%q" .Module.URL}})
{{end}}
// ClientHead returns the elements the browser half of the bridge needs: an
// import map so bare specifiers like "react" resolve, and the entry module that
// fetches the payload and mounts it.
//
// Put it in the document head:
//
//	react.H("head", nil, react.Frag(ClientHead()...))
func ClientHead() []react.Node {
	return []react.Node{
		react.H("script", react.Props{
			"type": "importmap",
			"dangerouslySetInnerHTML": react.DangerousHTML{HTML: ` + "`" + `{{.ImportMap}}` + "`" + `},
		}),
		react.H("script", react.Props{"type": "module", "src": {{printf "%q" .EntryURL}}}),
	}
}

// MountID is the id of the element the client renders into. The page must
// contain an element with this id before the entry module runs.
const MountID = {{printf "%q" .MountID}}

// RSCPath is the URL the browser fetches the Flight payload from. The Go server
// must serve it with Content-Type: text/x-component.
const RSCPath = {{printf "%q" .RSCPath}}
`))

var entryTemplate = template.Must(template.New("entry").Parse(
	`// Generated by ` + "`react rsc`" + `. DO NOT EDIT.
//
// The browser half of the RSC bridge. It fetches the payload the Go server
// renders and mounts it with a real React root, so every client component in
// the tree gets its hooks, its state and its event handlers.

import { createFromFetch } from "react-server-dom-webpack/client.browser";
import { createRoot } from "react-dom/client";

// React resolves a client reference by awaiting each chunk and then requiring
// the module id. With no bundler involved both of those are simply the module's
// URL, so these two functions are the whole module system: import it, remember
// it, hand it back.
//
// They are globals because that is the interface React's client expects; a
// bundler would normally provide them.
const loaded = new Map();

globalThis.__webpack_chunk_load__ = async (url) => {
  if (!loaded.has(url)) {
    loaded.set(url, await import(/* @vite-ignore */ url));
  }
  return loaded.get(url);
};

globalThis.__webpack_require__ = (url) => loaded.get(url);

const container = document.getElementById({{printf "%q" .MountID}});
if (!container) {
  throw new Error(
    'react: no element with id "{{.MountID}}" to mount into. ' +
      "Add one to the page, or change MountID and regenerate."
  );
}

const root = createRoot(container);

createFromFetch(fetch({{printf "%q" .RSCPath}})).then(
  (tree) => root.render(tree),
  (error) => {
    console.error("react: could not load the server payload", error);
    throw error;
  }
);
`))
