// Upstream-parity metrics per library, aggregated from each repo's parity.json
// (emitted by the parity CI pipeline / the upstream-parity audit). Each library
// port is measured against the ORIGINAL library it mirrors by syncing that
// library's own test suite into Go and closing the gaps those tests expose.
//
// This file is regenerated by `go run ./genparity` at the repo root, which reads
// every submodule's parity.json; the seeded values below are updated as audits
// land so the landing always reports the current numbers.

export interface Parity {
  // upstream is the original library, as "owner/name".
  upstream: string;
  // before/after are the estimated parity percentages, pre and post audit.
  before: string;
  after: string;
  // casesSynced is how many of the upstream's own test vectors are encoded as Go
  // parity tests; gapsClosed is how many behavior gaps those tests revealed and
  // that were fixed.
  casesSynced: number;
  gapsClosed: number;
}

// PARITY is keyed by Lib.id.
export const PARITY: Record<string, Parity> = {
  moment: { upstream: 'moment/moment', before: '84%', after: '98%', casesSynced: 319, gapsClosed: 9 },
  lodash: { upstream: 'lodash/lodash', before: '90%', after: '98%', casesSynced: 450, gapsClosed: 6 },
  handlebars: { upstream: 'handlebars-lang/handlebars.js', before: '87%', after: '97%', casesSynced: 192, gapsClosed: 11 },
};
