// Upstream-parity metrics per library, aggregated from each repo's parity.json
// (emitted by the parity CI pipeline / the upstream-parity audit). Each library
// port is measured against the ORIGINAL library it mirrors by syncing that
// library's own test suite into Go and closing the gaps those tests expose.
//
// Regenerated by `go run ./genparity <dir-of-repos>` (reads every repo's
// parity.json); keys are Lib.id.

export interface Parity {
  // upstream is the original library, as "owner/name".
  upstream: string;
  // before/after are the estimated parity percentages, pre and post audit.
  before: string;
  after: string;
  // casesSynced is how many of the upstream's own test vectors are encoded as Go
  // parity tests; gapsClosed is how many behavior gaps those tests revealed and
  // that were fixed.
  casesSynced: number;
  gapsClosed: number;
}

// PARITY is keyed by Lib.id.
export const PARITY: Record<string, Parity> = {
  algebra: { upstream: 'sympy/sympy', before: '91%', after: '100%', casesSynced: 56, gapsClosed: 3 },
  axios: { upstream: 'axios/axios', before: '66%', after: '100%', casesSynced: 38, gapsClosed: 13 },
  chalk: { upstream: 'chalk/chalk', before: '83%', after: '100%', casesSynced: 30, gapsClosed: 5 },
  cheerio: { upstream: 'cheeriojs/cheerio', before: '92%', after: '100%', casesSynced: 60, gapsClosed: 5 },
  express: { upstream: 'expressjs/express', before: '73%', after: '100%', casesSynced: 33, gapsClosed: 9 },
  fastmcp: { upstream: 'jlowin/fastmcp', before: '82%', after: '99%', casesSynced: 161, gapsClosed: 12 },
  gltf: { upstream: 'KhronosGroup/glTF', before: '94%', after: '100%', casesSynced: 36, gapsClosed: 2 },
  handlebars: { upstream: 'handlebars-lang/handlebars.js', before: '87%', after: '97%', casesSynced: 192, gapsClosed: 11 },
  jest: { upstream: 'jestjs/jest', before: '98%', after: '100%', casesSynced: 90, gapsClosed: 1 },
  jwt: { upstream: 'auth0/node-jsonwebtoken', before: '93%', after: '100%', casesSynced: 30, gapsClosed: 2 },
  liveview: { upstream: 'phoenixframework/phoenix_live_view', before: '90%', after: '100%', casesSynced: 18, gapsClosed: 2 },
  lodash: { upstream: 'lodash/lodash', before: '90%', after: '98%', casesSynced: 450, gapsClosed: 6 },
  lucene: { upstream: 'apache/lucene', before: '22%', after: '100%', casesSynced: 55, gapsClosed: 3 },
  matplotlib: { upstream: 'matplotlib/matplotlib', before: '78%', after: '100%', casesSynced: 8, gapsClosed: 2 },
  migrate: { upstream: 'rails/rails', before: '87%', after: '100%', casesSynced: 15, gapsClosed: 2 },
  moment: { upstream: 'moment/moment', before: '84%', after: '98%', casesSynced: 319, gapsClosed: 9 },
  morgan: { upstream: 'expressjs/morgan', before: '81%', after: '100%', casesSynced: 54, gapsClosed: 3 },
  nodemailer: { upstream: 'nodemailer/nodemailer', before: '0%', after: '100%', casesSynced: 78, gapsClosed: 78 },
  numpy: { upstream: 'numpy/numpy', before: '94%', after: '100%', casesSynced: 46, gapsClosed: 3 },
  oban: { upstream: 'sorentwo/oban', before: '80%', after: '100%', casesSynced: 41, gapsClosed: 3 },
  pandas: { upstream: 'pandas-dev/pandas', before: '74%', after: '100%', casesSynced: 27, gapsClosed: 7 },
  passport: { upstream: 'jaredhanson/passport', before: '26%', after: '100%', casesSynced: 34, gapsClosed: 6 },
  pdfkit: { upstream: 'foliojs/pdfkit', before: '19%', after: '100%', casesSynced: 58, gapsClosed: 47 },
  prisma: { upstream: 'prisma/prisma', before: '85%', after: '100%', casesSynced: 27, gapsClosed: 4 },
  puppeteer: { upstream: 'puppeteer/puppeteer', before: '72%', after: '94%', casesSynced: 24, gapsClosed: 8 },
  quartz: { upstream: 'quartz-scheduler/quartz', before: '69%', after: '100%', casesSynced: 26, gapsClosed: 3 },
  redis: { upstream: 'redis/redis', before: '93%', after: '100%', casesSynced: 110, gapsClosed: 5 },
  sharp: { upstream: 'lovell/sharp', before: '68%', after: '100%', casesSynced: 22, gapsClosed: 7 },
  sled: { upstream: 'spacejam/sled', before: '90%', after: '100%', casesSynced: 30, gapsClosed: 3 },
  socketio: { upstream: 'socketio/socket.io', before: '90%', after: '100%', casesSynced: 20, gapsClosed: 4 },
  sqlite: { upstream: 'sqlite/sqlite', before: '92%', after: '100%', casesSynced: 73, gapsClosed: 5 },
  streamlit: { upstream: 'streamlit/streamlit', before: '76%', after: '93%', casesSynced: 31, gapsClosed: 3 },
};
