// LEGACY — HAND-WRITTEN. DO NOT USE IN NEW CODE.
//
// This map was maintained by hand (and by a since-retired generator), so its
// numbers are *claims*, not measurements: nothing re-checks them when a harness
// re-runs, and the `before`/`after`/`gapsClosed` fields have no counterpart in
// any harness output at all.
//
// The measured source of truth is **api/_data/parity.json**, generated on every
// build by `scripts/build-graph-data.ts` (`pnpm build:graph`, also the `prebuild`
// hook) directly out of the harnesses under `parity/**`:
// `parity.json` totals, `cases/*.json`, the `COVERAGE.md` API inventory and
// `security.json`. Read it through the memoized loaders in `api/_lib/data.ts`:
//
//     import { getParity, getParityFor } from '../_lib/data.ts';
//     const express = getParityFor('express');   // null when unknown
//     express?.parityPercent;                    // measured, per case
//     express?.coverage;                         // per-symbol inventory
//     express?.nested?.qs;                       // the qs port, scored separately
//
// This file is kept only because existing code still imports PARITY (the graph
// builder reads `upstream`/`after` from it, best-effort). Do not add entries and
// do not quote these numbers in the UI.
//
// ---------------------------------------------------------------------------
//
// Upstream-parity metrics per library, aggregated from each repo's parity.json.
//
// Each number is MEASURED, not asserted: the port's parity suite installs the
// original library — the real npm/PyPI/RubyGems package — runs it in its own
// runtime, asks it and the Go port the same questions, and records every
// disagreement. See github.com/malcolmston/go/parity.
//
// GENERATED by `go run ./genparity` — do not edit by hand.

export interface Parity {
  /** The original library this port is measured against, as a GitHub slug. */
  upstream: string;
  /** Score on the same case set using the previous run's failures. */
  before: string;
  /** Share of cases where the port agrees with upstream, measured now. */
  after: string;
  casesSynced: number;
  gapsClosed: number;

  // Present for ports on the measured schema (parity.json v2).

  /** live: upstream ran here. golden: its recorded answers were replayed. */
  mode?: 'live' | 'golden' | 'mixed' | 'unmeasured';
  /** Runtime the original library ran in: node, python, ruby, … */
  runtime?: string;
  /** The exact upstream package that answered, e.g. "chalk@5.3.0". */
  upstreamPkg?: string;
  matched?: number;
  differing?: number;
  skipped?: number;
  /** Cross-compile targets attempted, and how many built. */
  platforms?: number;
  platformsOK?: number;
  measuredAt?: string;
}

// PARITY is keyed by Lib.id.
export const PARITY: Record<string, Parity> = {
  algebra: { upstream: "sympy/sympy", before: "91%", after: "100%", casesSynced: 56, gapsClosed: 3 },
  axios: { upstream: "axios/axios", before: "66%", after: "100%", casesSynced: 38, gapsClosed: 13 },
  chalk: { upstream: "chalk/chalk", before: "83%", after: "100%", casesSynced: 30, gapsClosed: 7 },
  cheerio: { upstream: "cheeriojs/cheerio", before: "92%", after: "100%", casesSynced: 60, gapsClosed: 5 },
  express: { upstream: "expressjs/express", before: "73%", after: "100%", casesSynced: 33, gapsClosed: 9 },
  fastmcp: { upstream: "jlowin/fastmcp", before: "82%", after: "99%", casesSynced: 161, gapsClosed: 12 },
  gltf: { upstream: "KhronosGroup/glTF", before: "94%", after: "100%", casesSynced: 36, gapsClosed: 2 },
  handlebars: { upstream: "handlebars-lang/handlebars.js", before: "87%", after: "97%", casesSynced: 192, gapsClosed: 11 },
  jest: { upstream: "jestjs/jest", before: "98%", after: "100%", casesSynced: 90, gapsClosed: 1 },
  jose: { upstream: "panva/jose", before: "0%", after: "100%", casesSynced: 55, gapsClosed: 7 },
  jq: { upstream: "jqlang/jq", before: "0%", after: "92.5%", casesSynced: 782, gapsClosed: 109 },
  jwt: { upstream: "auth0/node-jsonwebtoken", before: "93%", after: "100%", casesSynced: 30, gapsClosed: 2 },
  liveview: { upstream: "phoenixframework/phoenix_live_view", before: "90%", after: "100%", casesSynced: 18, gapsClosed: 2 },
  lodash: { upstream: "lodash/lodash", before: "90%", after: "98%", casesSynced: 450, gapsClosed: 6 },
  lucene: { upstream: "apache/lucene", before: "22%", after: "100%", casesSynced: 55, gapsClosed: 3 },
  markdown: { upstream: "commonmark/commonmark-spec", before: "0%", after: "100%", casesSynced: 652, gapsClosed: 652 },
  matplotlib: { upstream: "matplotlib/matplotlib", before: "78%", after: "100%", casesSynced: 8, gapsClosed: 2 },
  migrate: { upstream: "rails/rails", before: "87%", after: "100%", casesSynced: 15, gapsClosed: 2 },
  moment: { upstream: "moment/moment", before: "84%", after: "98%", casesSynced: 319, gapsClosed: 9 },
  morgan: { upstream: "expressjs/morgan", before: "81%", after: "100%", casesSynced: 54, gapsClosed: 8 },
  nodemailer: { upstream: "nodemailer/nodemailer", before: "0%", after: "100%", casesSynced: 78, gapsClosed: 78 },
  numpy: { upstream: "numpy/numpy", before: "94%", after: "100%", casesSynced: 46, gapsClosed: 3 },
  oban: { upstream: "sorentwo/oban", before: "80%", after: "100%", casesSynced: 41, gapsClosed: 3 },
  pandas: { upstream: "pandas-dev/pandas", before: "74%", after: "100%", casesSynced: 27, gapsClosed: 7 },
  passport: { upstream: "jaredhanson/passport", before: "26%", after: "100%", casesSynced: 34, gapsClosed: 6 },
  pdfkit: { upstream: "foliojs/pdfkit", before: "19%", after: "100%", casesSynced: 58, gapsClosed: 47 },
  prisma: { upstream: "prisma/prisma", before: "85%", after: "100%", casesSynced: 27, gapsClosed: 4 },
  puppeteer: { upstream: "puppeteer/puppeteer", before: "72%", after: "94%", casesSynced: 24, gapsClosed: 8 },
  quartz: { upstream: "quartz-scheduler/quartz", before: "69%", after: "100%", casesSynced: 26, gapsClosed: 3 },
  redis: { upstream: "redis/redis", before: "93%", after: "100%", casesSynced: 110, gapsClosed: 5 },
  rrule: { upstream: "dateutil/dateutil", before: "0%", after: "99.6%", casesSynced: 256, gapsClosed: 0 },
  sharp: { upstream: "lovell/sharp", before: "68%", after: "100%", casesSynced: 22, gapsClosed: 7 },
  sled: { upstream: "spacejam/sled", before: "90%", after: "100%", casesSynced: 30, gapsClosed: 3 },
  'socket.io': { upstream: "socketio/socket.io", before: "90%", after: "100%", casesSynced: 20, gapsClosed: 4 },
  sqlite: { upstream: "sqlite/sqlite", before: "92%", after: "100%", casesSynced: 73, gapsClosed: 5 },
  streamlit: { upstream: "streamlit/streamlit", before: "93%", after: "96%", casesSynced: 47, gapsClosed: 8 },
  yaml: { upstream: "yaml/yaml-test-suite", before: "0%", after: "99.7%", casesSynced: 373, gapsClosed: 372 },
};
