# frozen_string_literal: true
#
# Upstream (rails/rails ActiveRecord) parity runner for the `migrate` port.
#
# Speaks the JSON-Lines contract described in parity/HARNESS.md: one JSON object
# per line on stdin, exactly one JSON object per line on stdout, never exiting
# because a case failed.
#
# Two case groups are understood:
#
#   fn = "ddl"      args = [[op, ...]]
#       Runs a script of SchemaStatements calls straight on the connection and
#       reports a canonical description of the resulting SQLite schema.
#
#   fn = "migrate"  args = [{"migrations": [...], "script": [...]}]
#       Registers migrations and drives ActiveRecord::MigrationContext through a
#       script of up/down/redo/migrate_to steps, reporting version bookkeeping
#       plus the schema after every step.
#
# The emitted value has four top-level keys. Only "steps" and "schema" are
# compared by the harness; "sql" (the statements each side actually emitted) and
# "raw" (un-normalised names, error texts) are diagnostics.

require "json"
require "tmpdir"
require "fileutils"
require "active_record"

ActiveRecord::Migration.verbose = false
ActiveRecord.validate_migration_timestamps = false
ActiveRecord::Base.logger = nil

BOOKKEEPING = ["schema_migrations", "ar_internal_metadata"].freeze

# --------------------------------------------------------------- SQL recording

# SqlLog captures every statement ActiveRecord sends to SQLite so type-mapping
# differences stay visible even though the harness compares the read-back schema
# rather than the SQL text.
class SqlLog
  def initialize
    @stmts = []
    @on = false
    @sub = ActiveSupport::Notifications.subscribe("sql.active_record") do |*args|
      next unless @on
      sql = ActiveSupport::Notifications::Event.new(*args).payload[:sql].to_s
      @stmts << sql.gsub(/\s+/, " ").strip unless boring?(sql)
    end
  end

  def boring?(sql)
    s = sql.strip
    s.empty? ||
      s.start_with?("PRAGMA", "pragma") ||
      s =~ /\ASELECT\b/i ||
      s =~ /\A(BEGIN|COMMIT|ROLLBACK|SAVEPOINT|RELEASE)\b/i ||
      s.include?("ar_internal_metadata") ||
      s.include?("schema_migrations")
  end

  def capture
    @stmts = []
    @on = true
    yield
  ensure
    @on = false
  end

  def statements
    @stmts
  end
end

SQL = SqlLog.new

# ------------------------------------------------------------- schema readback

# Schema reads the live SQLite catalogue back into a canonical, language-neutral
# description. Normalisations (documented in COVERAGE.md):
#   * declared types are upper-cased and whitespace-collapsed
#   * an INTEGER PRIMARY KEY is reported NOT NULL (SQLite forbids a null rowid)
#   * autogenerated index names collapse to "<default>" / "<autoindex>"
#   * check-constraint names collapse to "<auto>" (both sides invent opaque ones)
module Schema
  module_function

  def conn
    ActiveRecord::Base.lease_connection
  end

  def rows(sql)
    conn.raw_connection.execute(sql)
  end

  def table_names
    rows("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
      .map { |r| r["name"] }
      .reject { |n| BOOKKEEPING.include?(n) }
  end

  def table_sql(name)
    r = rows("SELECT sql FROM sqlite_master WHERE type='table' AND name=#{quote(name)}").first
    r ? r["sql"].to_s : ""
  end

  def quote(s)
    "'" + s.gsub("'", "''") + "'"
  end

  def norm_type(t)
    t.to_s.gsub(/\s+/, " ").strip.upcase
  end

  def columns(table)
    rows("PRAGMA table_info(#{conn.quote_table_name(table)})").map do |r|
      pk = r["pk"].to_i
      type = norm_type(r["type"])
      notnull = r["notnull"].to_i != 0
      notnull = true if pk > 0 && type == "INTEGER"
      {
        "name" => r["name"],
        "type" => type,
        "notnull" => notnull,
        "default" => r["dflt_value"].nil? ? nil : r["dflt_value"].to_s,
        "pk" => pk,
      }
    end
  end

  def index_shape(name, table, cols)
    return "<default>" if name == "index_#{table}_on_#{cols.join('_and_')}"
    return "<autoindex>" if name.start_with?("sqlite_autoindex_")
    name
  end

  def indexes(table)
    out = rows("PRAGMA index_list(#{conn.quote_table_name(table)})").map do |r|
      name = r["name"]
      cols = rows("PRAGMA index_info(#{conn.quote_table_name(name)})")
             .sort_by { |i| i["seqno"].to_i }
             .map { |i| i["name"].nil? ? "<expr>" : i["name"] }
      {
        "name" => index_shape(name, table, cols),
        "raw" => name,
        "unique" => r["unique"].to_i != 0,
        "partial" => r["partial"].to_i != 0,
        "origin" => r["origin"],
        "columns" => cols,
      }
    end
    out.sort_by { |i| [i["name"], i["columns"].join(","), i["raw"]] }
  end

  def foreign_keys(table)
    rows("PRAGMA foreign_key_list(#{conn.quote_table_name(table)})").map do |r|
      {
        "table" => r["table"],
        "from" => r["from"],
        "to" => r["to"].nil? ? nil : r["to"],
        "on_delete" => r["on_delete"].to_s.upcase,
        "on_update" => r["on_update"].to_s.upcase,
      }
    end.sort_by { |f| [f["table"].to_s, f["from"].to_s] }
  end

  # checks extracts CHECK(...) bodies from a table's CREATE statement by paren
  # matching, since SQLite exposes no pragma for them.
  def checks(sql)
    out = []
    i = 0
    while (m = sql.index(/CHECK\s*\(/i, i))
      md = sql[m..].match(/\ACHECK\s*\(/i)
      open = m + md[0].length - 1
      depth = 0
      j = open
      while j < sql.length
        depth += 1 if sql[j] == "("
        depth -= 1 if sql[j] == ")"
        break if depth.zero?
        j += 1
      end
      body = sql[(open + 1)...j].to_s
      out << { "name" => "<auto>", "raw" => check_name(sql, m), "expr" => body.gsub('"', "").gsub(/\s+/, " ").strip }
      i = j + 1
    end
    out.sort_by { |c| c["expr"] }
  end

  def check_name(sql, check_at)
    before = sql[0...check_at]
    md = before.match(/CONSTRAINT\s+("([^"]+)"|[A-Za-z_][A-Za-z0-9_]*)\s*\z/)
    return nil unless md
    md[2] || md[1]
  end

  def snapshot
    tables = table_names.map do |t|
      sql = table_sql(t)
      {
        "name" => t,
        "columns" => columns(t),
        "indexes" => indexes(t),
        "foreign_keys" => foreign_keys(t),
        "checks" => checks(sql),
      }
    end
    { "tables" => tables }
  end

  def brief
    table_names.map { |t| { "name" => t, "columns" => columns(t).map { |c| c["name"] } } }
  end

  def raw_sql_dump
    table_names.to_h { |t| [t, table_sql(t).gsub(/\s+/, " ").strip] }
  end

  def raw_names
    table_names.to_h do |t|
      [t, {
        "indexes" => indexes(t).map { |i| i["raw"] },
        "checks" => checks(table_sql(t)).map { |c| c["raw"] },
      }]
    end
  end
end

# err_text renders an exception (and its cause) as a single diagnostic line. The
# harness never compares error text, only whether a case failed.
def err_text(e)
  parts = ["#{e.class}: #{e.message.to_s.gsub(/\s+/, ' ').strip}"]
  parts << "cause=#{e.cause.class}: #{e.cause.message.to_s.gsub(/\s+/, ' ').strip}" if e.cause
  parts.join(" | ")[0, 400]
end

# ------------------------------------------------------------- op interpreter

module Ops
  module_function

  def sym(v)
    v.nil? ? nil : v.to_sym
  end

  # col_options translates the neutral column spec into ActiveRecord keywords.
  def col_options(spec)
    o = {}
    o[:limit] = spec["limit"] if spec.key?("limit")
    o[:null] = spec["null"] if spec.key?("null")
    o[:precision] = spec["precision"] if spec.key?("precision")
    o[:scale] = spec["scale"] if spec.key?("scale")
    o[:default] = spec["default"] if spec.key?("default")
    o[:default] = -> { spec["default_raw"] } if spec.key?("default_raw")
    o[:primary_key] = spec["primary_key"] if spec.key?("primary_key")
    o[:array] = spec["array"] if spec.key?("array")
    o[:values] = spec["values"] if spec.key?("values")
    o[:comment] = spec["comment"] if spec.key?("comment")
    o
  end

  def ref_options(spec)
    o = {}
    o[:index] = spec["index"] if spec.key?("index")
    o[:foreign_key] = spec["foreign_key"] if spec.key?("foreign_key")
    o[:polymorphic] = spec["polymorphic"] if spec.key?("polymorphic")
    o[:null] = spec["null"] if spec.key?("null")
    o[:to_table] = spec["to_table"] if spec.key?("to_table")
    # "type" on a reference spec is the neutral op/column tag ("references"), so
    # an explicit reference column type is spelled "ref_type".
    o[:type] = sym(spec["ref_type"]) if spec.key?("ref_type")
    o
  end

  def add_column_to(t, spec)
    case spec["type"]
    when "timestamps" then t.timestamps
    when "references" then t.references(spec["name"], **ref_options(spec))
    when "check" then t.check_constraint(spec["expression"], name: spec["name"])
    else t.column(spec["name"], sym(spec["type"]), **col_options(spec))
    end
  end

  def index_options(op)
    o = {}
    o[:unique] = op["unique"] if op.key?("unique")
    o[:name] = op["name"] if op.key?("name")
    o[:where] = op["where"] if op.key?("where")
    o[:using] = op["using"] if op.key?("using")
    o
  end

  def fk_options(op)
    o = {}
    o[:column] = op["column"] if op.key?("column")
    o[:primary_key] = op["primary_key"] if op.key?("primary_key")
    o[:on_delete] = sym(op["on_delete"]) if op.key?("on_delete")
    o[:on_update] = sym(op["on_update"]) if op.key?("on_update")
    o[:name] = op["name"] if op.key?("name")
    o
  end

  def table_options(op)
    o = {}
    o[:id] = op["id"] == false ? false : sym(op["id"]) if op.key?("id")
    o[:primary_key] = op["primary_key"] if op.key?("primary_key")
    o[:if_not_exists] = op["if_not_exists"] if op.key?("if_not_exists")
    o
  end

  # apply_change dispatches one entry of a change_table block onto the bulk
  # alteration builder t.
  def apply_change(t, ch)
    case ch["kind"]
    when "column" then t.column(ch["name"], sym(ch["type"]), **col_options(ch))
    when "change" then t.change(ch["name"], sym(ch["type"]), **col_options(ch))
    when "remove" then t.remove(*ch["names"])
    when "rename" then t.rename(ch["from"], ch["to"])
    when "index" then t.index(ch["columns"], **{ unique: ch["unique"] }.compact)
    when "remove_index" then t.remove_index(name: ch["name"])
    when "timestamps" then t.timestamps
    when "references" then t.references(ch["name"], **ref_options(ch))
    else raise ArgumentError, "unknown change_table entry #{ch['kind'].inspect}"
    end
  end

  # apply dispatches one neutral op onto c, which is either the connection
  # (group "ddl") or a Migration instance (group "migrate"); both expose the
  # SchemaStatements API.
  def apply(c, op)
    case op["op"]
    when "create_table"
      c.create_table(op["table"], **table_options(op)) do |t|
        (op["columns"] || []).each { |spec| add_column_to(t, spec) }
      end
    when "drop_table"
      c.drop_table(op["table"])
    when "rename_table"
      c.rename_table(op["from"], op["to"])
    when "change_table"
      c.change_table(op["table"]) do |t|
        (op["changes"] || []).each { |ch| apply_change(t, ch) }
      end
    when "add_column"
      c.add_column(op["table"], op["name"], sym(op["type"]), **col_options(op))
    when "remove_column"
      c.remove_column(op["table"], op["name"])
    when "change_column"
      c.change_column(op["table"], op["name"], sym(op["type"]), **col_options(op))
    when "change_column_null"
      c.change_column_null(op["table"], op["column"], op["null"])
    when "change_column_default"
      if op.key?("default_raw")
        c.change_column_default(op["table"], op["column"], -> { op["default_raw"] })
      else
        c.change_column_default(op["table"], op["column"], op["default"])
      end
    when "rename_column"
      c.rename_column(op["table"], op["from"], op["to"])
    when "add_index"
      c.add_index(op["table"], op["columns"].length == 1 ? op["columns"].first : op["columns"], **index_options(op))
    when "remove_index"
      if op.key?("name")
        c.remove_index(op["table"], name: op["name"])
      else
        c.remove_index(op["table"], op["columns"])
      end
    when "rename_index"
      c.rename_index(op["table"], op["from"], op["to"])
    when "add_timestamps"
      c.add_timestamps(op["table"])
    when "remove_timestamps"
      c.remove_timestamps(op["table"])
    when "add_reference"
      c.add_reference(op["table"], op["name"], **ref_options(op))
    when "remove_reference"
      c.remove_reference(op["table"], op["name"], **ref_options(op))
    when "add_foreign_key"
      c.add_foreign_key(op["from"], op["to"], **fk_options(op))
    when "remove_foreign_key"
      c.remove_foreign_key(op["from"], op["to"], **fk_options(op))
    when "add_check_constraint"
      c.add_check_constraint(op["table"], op["expression"], name: op["name"])
    when "remove_check_constraint"
      c.remove_check_constraint(op["table"], op["expression"], name: op["name"])
    when "add_unique_constraint"
      c.add_unique_constraint(op["table"], op["columns"], name: op["name"])
    when "create_join_table"
      c.create_join_table(op["table1"], op["table2"])
    when "drop_join_table"
      c.drop_join_table(op["table1"], op["table2"])
    when "truncate_table"
      c.truncate(op["table"])
    when "execute", "raw_sql"
      # ActiveRecord's raw-SQL migration facility is #execute; it hands the whole
      # script to SQLite rather than splitting it itself.
      c.execute(op["sql"])
    when "insert"
      c.execute(op["sql"])
    else
      raise ArgumentError, "unknown op #{op['op'].inspect}"
    end
  end
end

# ------------------------------------------------------------------- databases

# with_db creates a fresh SQLite database in its own temp directory, yields, and
# removes the directory again, so no case can observe another's state.
def with_db
  dir = Dir.mktmpdir("migrate-parity-")
  begin
    ActiveRecord::Base.establish_connection(
      adapter: "sqlite3",
      database: File.join(dir, "parity.sqlite3"),
    )
    ActiveRecord::Base.lease_connection.execute("PRAGMA foreign_keys = ON")
    yield
  ensure
    begin
      ActiveRecord::Base.connection_handler.clear_all_connections!
    rescue StandardError
      nil
    end
    FileUtils.remove_entry(dir) rescue nil
  end
end

# -------------------------------------------------------------- group 1: DDL

def run_ddl(ops)
  steps = []
  errors = []
  sql = []
  with_db do
    ops.each_with_index do |op, i|
      ok = true
      err = nil
      SQL.capture do
        begin
          Ops.apply(ActiveRecord::Base.lease_connection, op)
        rescue Exception => e # rubocop:disable Lint/RescueException
          ok = false
          err = err_text(e)
        end
      end
      sql.concat(SQL.statements)
      steps << { "i" => i, "op" => op["op"], "ok" => ok }
      errors << { "i" => i, "error" => err } unless ok
    end
    {
      "steps" => steps,
      "schema" => Schema.snapshot,
      "sql" => sql,
      "raw" => { "step_errors" => errors, "names" => Schema.raw_names, "tables_sql" => Schema.raw_sql_dump },
    }
  end
end

# --------------------------------------------------- group 2: migration state

# PARITY_OPS holds the op lists of the migrations for the case being run; the
# generated migration files call back into it so no Ruby codegen is needed.
PARITY_OPS = {}

def write_migration_files(dir, migrations, seq)
  migrations.each do |m|
    version = m["version"].to_i
    name = m["name"]
    base = "pm#{seq}_v#{version}"
    klass = base.camelize
    # A migration whose spec omits "down" entirely gets no down method, so
    # ActiveRecord raises IrreversibleMigration exactly as the port refuses a
    # migration with no Down direction. An explicitly empty "down" array gets an
    # empty method, which is a legitimate no-op rollback.
    down_method =
      if m.key?("down")
        <<~RUBY
          def down
            PARITY_OPS.fetch(#{version}).fetch("down", []).each { |op| Ops.apply(self, op) }
          end
        RUBY
      else
        ""
      end
    # ActiveRecord derives the class name from the file name, so the file name
    # must camelize to the class we just wrote.
    File.write(File.join(dir, "#{version}_#{base}.rb"), <<~RUBY)
      class #{klass} < ActiveRecord::Migration[8.0]
        def up
          PARITY_OPS.fetch(#{version}).fetch("up", []).each { |op| Ops.apply(self, op) }
        end

        #{down_method.strip.gsub("\n", "\n  ")}
      end
    RUBY
    PARITY_OPS[version] = m
  end
end

# migration_status projects ActiveRecord's migrations_status into the neutral
# shape {version, applied} so it can be compared with Migrator.Status.
def migration_status(ctx)
  ctx.migrations_status.map { |st, version, _name| { "version" => version.to_i, "applied" => st == "up" } }
     .sort_by { |h| h["version"] }
rescue StandardError
  []
end

def applied_versions(ctx)
  ctx.get_all_versions.map(&:to_i).sort
rescue StandardError
  []
end

def bookkeeping_shape
  cols = Schema.rows("PRAGMA table_info(schema_migrations)").map do |r|
    { "name" => r["name"], "type" => Schema.norm_type(r["type"]), "notnull" => r["notnull"].to_i != 0, "pk" => r["pk"].to_i }
  end
  { "table" => "schema_migrations", "columns" => cols }
rescue StandardError
  { "table" => "schema_migrations", "columns" => [] }
end

$mig_seq = 0

def run_migrate(spec)
  $mig_seq += 1
  seq = $mig_seq
  migrations = spec["migrations"] || []
  script = spec["script"] || []
  steps = []
  errors = []
  sql = []
  with_db do
    dir = Dir.mktmpdir("migrate-parity-files-")
    begin
      PARITY_OPS.clear
      write_migration_files(dir, migrations, seq)
      ctx = ActiveRecord::MigrationContext.new(dir)
      # Provision the bookkeeping table up front, mirroring the port's
      # Migrator.EnsureSchemaTable, so a status query before the first migration
      # is comparable on both sides.
      ctx.schema_migration.create_table
      ctx.internal_metadata.create_table

      script.each_with_index do |st, i|
        ok = true
        err = nil
        SQL.capture do
          begin
            case st["op"]
            when "up" then ctx.migrate
            when "up_n" then ctx.forward(st["n"].to_i)
            when "rollback" then ctx.rollback(st["n"] ? st["n"].to_i : 1)
            when "down_all" then ctx.migrate(0)
            when "migrate_to" then ctx.migrate(st["version"].to_i)
            when "redo" then (ctx.rollback(1); ctx.forward(1))
            when "version", "status" then nil
            else raise ArgumentError, "unknown migrate step #{st['op'].inspect}"
            end
          rescue Exception => e # rubocop:disable Lint/RescueException
            ok = false
            err = err_text(e)
          end
        end
        sql.concat(SQL.statements)
        steps << {
          "i" => i,
          "op" => st["op"],
          "ok" => ok,
          "version" => applied_versions(ctx).max || 0,
          "applied" => applied_versions(ctx),
          "status" => migration_status(ctx),
          "tables" => Schema.brief,
        }
        errors << { "i" => i, "error" => err } unless ok
      end

      value = {
        "steps" => steps,
        "schema" => Schema.snapshot,
        "sql" => sql,
        "raw" => {
          "step_errors" => errors,
          "names" => Schema.raw_names,
          "tables_sql" => Schema.raw_sql_dump,
          "bookkeeping" => bookkeeping_shape,
        },
      }
      value["bookkeeping"] = bookkeeping_shape if spec["report_bookkeeping"]
      value
    ensure
      FileUtils.remove_entry(dir) rescue nil
    end
  end
end

# ------------------------------------------------------------------- protocol

$stdout.sync = true
$stdin.each_line do |line|
  line = line.strip
  next if line.empty?
  req = begin
    JSON.parse(line)
  rescue StandardError => e
    $stdout.puts(JSON.generate({ "id" => "?", "ok" => false, "error" => "bad request: #{e.message}" }))
    next
  end
  id = req["id"]
  begin
    value =
      case req["fn"]
      when "ddl" then run_ddl(req["args"][0])
      when "migrate" then run_migrate(req["args"][0])
      else raise ArgumentError, "unknown fn #{req['fn'].inspect}"
      end
    $stdout.puts(JSON.generate({ "id" => id, "ok" => true, "value" => value }))
  rescue Exception => e # rubocop:disable Lint/RescueException
    $stdout.puts(JSON.generate({ "id" => id, "ok" => false, "error" => err_text(e) }))
  end
end
